<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 12 Controle Sintético e Estimação Contrafactual | Curso de Inferência Causal</title>
  <meta name="description" content="Capítulo 12 Controle Sintético e Estimação Contrafactual | Curso de Inferência Causal" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 12 Controle Sintético e Estimação Contrafactual | Curso de Inferência Causal" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 12 Controle Sintético e Estimação Contrafactual | Curso de Inferência Causal" />
  
  
  

<meta name="author" content="Manoel Galdino" />


<meta name="date" content="2026-06-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="interferência-spillover-e-dinâmica.html"/>
<link rel="next" href="llms-e-outras.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Causalidade</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="11-Synth.html"><a href="#introdu%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>1</b> Introdução</a>
<ul>
<li class="chapter" data-level="1.1" data-path="11-Synth.html"><a href="#a-revolu%C3%A7%C3%A3o-da-credibilidade-em-ci%C3%AAncia-pol%C3%ADtica"><i class="fa fa-check"></i><b>1.1</b> A revolução da credibilidade em ciência política</a></li>
<li class="chapter" data-level="1.2" data-path="11-Synth.html"><a href="#revis%C3%A3o-de-regress%C3%A3o"><i class="fa fa-check"></i><b>1.2</b> Revisão de Regressão</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="11-Synth.html"><a href="#teorema-da-anatomia-da-regress%C3%A3o"><i class="fa fa-check"></i><b>1.2.1</b> Teorema da Anatomia da Regressão</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="11-Synth.html"><a href="#infer%C3%AAncia"><i class="fa fa-check"></i><b>1.3</b> Inferência</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="11-Synth.html"><a href="#generaliza%C3%A7%C3%A3o-amostral-vs.-generaliza%C3%A7%C3%A3o-causal"><i class="fa fa-check"></i><b>1.3.1</b> Generalização amostral vs. generalização causal</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1.3.2</b> Incerteza com o universo dos casos</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#validade-externa"><i class="fa fa-check"></i><b>1.3.3</b> Validade externa</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="11-Synth.html"><a href="#resumo-e-pr%C3%B3ximos-passos"><i class="fa fa-check"></i><b>1.4</b> Resumo e próximos passos</a></li>
<li class="chapter" data-level="1.5" data-path="11-Synth.html"><a href="#refer%C3%AAncias"><i class="fa fa-check"></i><b>1.5</b> Referências</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="resultados-potenciais.html"><a href="resultados-potenciais.html"><i class="fa fa-check"></i><b>2</b> Resultados Potenciais</a>
<ul>
<li class="chapter" data-level="2.1" data-path="11-Synth.html"><a href="#da-intui%C3%A7%C3%A3o-comparativa-ao-modelo-formal"><i class="fa fa-check"></i><b>2.1</b> Da intuição comparativa ao modelo formal</a></li>
<li class="chapter" data-level="2.2" data-path="resultados-potenciais.html"><a href="resultados-potenciais.html#resultados-potenciais-potential-outcomes"><i class="fa fa-check"></i><b>2.2</b> Resultados Potenciais (<em>Potential Outcomes</em>)</a></li>
<li class="chapter" data-level="2.3" data-path="11-Synth.html"><a href="#nota%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>2.3</b> Notação</a></li>
<li class="chapter" data-level="2.4" data-path="11-Synth.html"><a href="#problema-fundamental-da-infer%C3%AAncia-causal"><i class="fa fa-check"></i><b>2.4</b> Problema Fundamental da Inferência Causal</a></li>
<li class="chapter" data-level="2.5" data-path="resultados-potenciais.html"><a href="resultados-potenciais.html#estimando"><i class="fa fa-check"></i><b>2.5</b> Estimando</a></li>
<li class="chapter" data-level="2.6" data-path="resultados-potenciais.html"><a href="resultados-potenciais.html#estimandos-mais-comuns"><i class="fa fa-check"></i><b>2.6</b> Estimandos Mais Comuns</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="resultados-potenciais.html"><a href="resultados-potenciais.html#ate"><i class="fa fa-check"></i><b>2.6.1</b> ATE</a></li>
<li class="chapter" data-level="2.6.2" data-path="resultados-potenciais.html"><a href="resultados-potenciais.html#att"><i class="fa fa-check"></i><b>2.6.2</b> ATT</a></li>
<li class="chapter" data-level="2.6.3" data-path="resultados-potenciais.html"><a href="resultados-potenciais.html#cate"><i class="fa fa-check"></i><b>2.6.3</b> CATE</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="11-Synth.html"><a href="#exerc%C3%ADcio-qual-o-estimando-e-o-estimador-se-poss%C3%ADvel"><i class="fa fa-check"></i><b>2.7</b> Exercício — Qual o estimando e o estimador (se possível)?</a></li>
<li class="chapter" data-level="2.8" data-path="11-Synth.html"><a href="#identifica%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>2.8</b> Identificação</a></li>
<li class="chapter" data-level="2.9" data-path="11-Synth.html"><a href="#identifica%C3%A7%C3%A3o-do-ate"><i class="fa fa-check"></i><b>2.9</b> Identificação do ATE</a></li>
<li class="chapter" data-level="2.10" data-path="11-Synth.html"><a href="#equa%C3%A7%C3%B5es-estruturais"><i class="fa fa-check"></i><b>2.10</b> Equações estruturais</a></li>
<li class="chapter" data-level="2.11" data-path="resultados-potenciais.html"><a href="resultados-potenciais.html#modelo-versus-desenho"><i class="fa fa-check"></i><b>2.11</b> Modelo versus Desenho</a></li>
<li class="chapter" data-level="2.12" data-path="11-Synth.html"><a href="#exerc%C3%ADcio-em-sala"><i class="fa fa-check"></i><b>2.12</b> Exercício em sala</a></li>
<li class="chapter" data-level="2.13" data-path="11-Synth.html"><a href="#resumo-e-pr%C3%B3ximos-passos-1"><i class="fa fa-check"></i><b>2.13</b> Resumo e próximos passos</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dags.html"><a href="dags.html"><i class="fa fa-check"></i><b>3</b> DAGs</a>
<ul>
<li class="chapter" data-level="3.1" data-path="11-Synth.html"><a href="#introdu%C3%A7%C3%A3o-1"><i class="fa fa-check"></i><b>3.1</b> Introdução</a></li>
<li class="chapter" data-level="3.2" data-path="11-Synth.html"><a href="#os-tipos-b%C3%A1sicos-de-dags"><i class="fa fa-check"></i><b>3.2</b> Os Tipos Básicos de DAGs</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="dags.html"><a href="dags.html#chain-cadeia"><i class="fa fa-check"></i><b>3.2.1</b> 1. Chain (cadeia)</a></li>
<li class="chapter" data-level="3.2.2" data-path="dags.html"><a href="dags.html#fork-garfo"><i class="fa fa-check"></i><b>3.2.2</b> 2. Fork (garfo)</a></li>
<li class="chapter" data-level="3.2.3" data-path="dags.html"><a href="dags.html#collider-colisor"><i class="fa fa-check"></i><b>3.2.3</b> 3. Collider (colisor)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="11-Synth.html"><a href="#simula%C3%A7%C3%A3o-no-r-ilustrando-o-collider-bias"><i class="fa fa-check"></i><b>3.3</b> Simulação no R: Ilustrando o Collider Bias</a></li>
<li class="chapter" data-level="3.4" data-path="11-Synth.html"><a href="#defini%C3%A7%C3%B5es-formais"><i class="fa fa-check"></i><b>3.4</b> Definições Formais</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="11-Synth.html"><a href="#caminhos-e-rela%C3%A7%C3%B5es-entre-n%C3%B3s"><i class="fa fa-check"></i><b>3.4.1</b> Caminhos e relações entre nós</a></li>
<li class="chapter" data-level="3.4.2" data-path="11-Synth.html"><a href="#d-separa%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>3.4.2</b> d-separação</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="dags.html"><a href="dags.html#controle-e-ajuste"><i class="fa fa-check"></i><b>3.5</b> Controle e Ajuste</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="dags.html"><a href="dags.html#condicionar-vs.-intervir"><i class="fa fa-check"></i><b>3.5.1</b> Condicionar vs. intervir</a></li>
<li class="chapter" data-level="3.5.2" data-path="dags.html"><a href="dags.html#o-que-acontece-ao-condicionar"><i class="fa fa-check"></i><b>3.5.2</b> O que acontece ao condicionar</a></li>
<li class="chapter" data-level="3.5.3" data-path="11-Synth.html"><a href="#o-que-d%C3%A1-errado-ao-condicionar-em-um-collider"><i class="fa fa-check"></i><b>3.5.3</b> O que dá errado ao condicionar em um collider</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="11-Synth.html"><a href="#o-crit%C3%A9rio-backdoor"><i class="fa fa-check"></i><b>3.6</b> O Critério Backdoor</a></li>
<li class="chapter" data-level="3.7" data-path="dags.html"><a href="dags.html#o-operador-do"><i class="fa fa-check"></i><b>3.7</b> O Operador <em>do</em></a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="dags.html"><a href="dags.html#observar-vs.-intervir"><i class="fa fa-check"></i><b>3.7.1</b> Observar vs. intervir</a></li>
<li class="chapter" data-level="3.7.2" data-path="dags.html"><a href="dags.html#quando-observar-intervir"><i class="fa fa-check"></i><b>3.7.2</b> Quando observar = intervir?</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="11-Synth.html"><a href="#limita%C3%A7%C3%B5es-dos-dags"><i class="fa fa-check"></i><b>3.8</b> Limitações dos DAGs</a></li>
<li class="chapter" data-level="3.9" data-path="11-Synth.html"><a href="#resumo-e-pr%C3%B3ximos-passos-2"><i class="fa fa-check"></i><b>3.9</b> Resumo e próximos passos</a></li>
<li class="chapter" data-level="3.10" data-path="11-Synth.html"><a href="#exerc%C3%ADcios"><i class="fa fa-check"></i><b>3.10</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="experimentos.html"><a href="experimentos.html"><i class="fa fa-check"></i><b>4</b> Experimentos</a>
<ul>
<li class="chapter" data-level="4.1" data-path="11-Synth.html"><a href="#introdu%C3%A7%C3%A3o-2"><i class="fa fa-check"></i><b>4.1</b> Introdução</a></li>
<li class="chapter" data-level="4.2" data-path="11-Synth.html"><a href="#recapitula%C3%A7%C3%A3o-sdo-e-vi%C3%A9s-de-sele%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>4.2</b> Recapitulação: SDO e viés de seleção</a></li>
<li class="chapter" data-level="4.3" data-path="11-Synth.html"><a href="#experimentos-aleat%C3%B3rios-e-identifica%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>4.3</b> Experimentos aleatórios e identificação</a></li>
<li class="chapter" data-level="4.4" data-path="11-Synth.html"><a href="#restri%C3%A7%C3%A3o-de-exclus%C3%A3o"><i class="fa fa-check"></i><b>4.4</b> Restrição de Exclusão</a></li>
<li class="chapter" data-level="4.5" data-path="11-Synth.html"><a href="#tipos-de-aleatoriza%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>4.5</b> Tipos de aleatorização</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="11-Synth.html"><a href="#aleatoriza%C3%A7%C3%A3o-de-bernoulli"><i class="fa fa-check"></i><b>4.5.1</b> Aleatorização de Bernoulli</a></li>
<li class="chapter" data-level="4.5.2" data-path="11-Synth.html"><a href="#aleatoriza%C3%A7%C3%A3o-completa"><i class="fa fa-check"></i><b>4.5.2</b> Aleatorização completa</a></li>
<li class="chapter" data-level="4.5.3" data-path="11-Synth.html"><a href="#aleatoriza%C3%A7%C3%A3o-condicional-em-bloco"><i class="fa fa-check"></i><b>4.5.3</b> Aleatorização condicional (em bloco)</a></li>
<li class="chapter" data-level="4.5.4" data-path="11-Synth.html"><a href="#precis%C3%A3o-da-aleatoriza%C3%A7%C3%A3o-em-bloco"><i class="fa fa-check"></i><b>4.5.4</b> Precisão da aleatorização em bloco</a></li>
<li class="chapter" data-level="4.5.5" data-path="11-Synth.html"><a href="#aleatoriza%C3%A7%C3%A3o-por-cluster"><i class="fa fa-check"></i><b>4.5.5</b> Aleatorização por cluster</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="experimentos.html"><a href="experimentos.html#experimentos-fatoriais"><i class="fa fa-check"></i><b>4.6</b> Experimentos fatoriais</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="experimentos.html"><a href="experimentos.html#desenho-2-times-2"><i class="fa fa-check"></i><b>4.6.1</b> Desenho <span class="math inline">\(2 \times 2\)</span></a></li>
<li class="chapter" data-level="4.6.2" data-path="11-Synth.html"><a href="#efeitos-principais-e-intera%C3%A7%C3%B5es"><i class="fa fa-check"></i><b>4.6.2</b> Efeitos principais e interações</a></li>
<li class="chapter" data-level="4.6.3" data-path="11-Synth.html"><a href="#efici%C3%AAncia-e-generaliza%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>4.6.3</b> Eficiência e generalização</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="experimentos.html"><a href="experimentos.html#experimentos-multi-arm"><i class="fa fa-check"></i><b>4.7</b> Experimentos multi-arm</a></li>
<li class="chapter" data-level="4.8" data-path="experimentos.html"><a href="experimentos.html#planejando-experimentos-com-declaredesign"><i class="fa fa-check"></i><b>4.8</b> Planejando experimentos com DeclareDesign</a></li>
<li class="chapter" data-level="4.9" data-path="11-Synth.html"><a href="#resumo-e-pr%C3%B3ximos-passos-3"><i class="fa fa-check"></i><b>4.9</b> Resumo e próximos passos</a></li>
<li class="chapter" data-level="4.10" data-path="11-Synth.html"><a href="#exerc%C3%ADcios-1"><i class="fa fa-check"></i><b>4.10</b> Exercícios</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="11-Synth.html"><a href="#exerc%C3%ADcio-1-cart%C3%B5es-postais-e-participa%C3%A7%C3%A3o-eleitoral"><i class="fa fa-check"></i><b>4.10.1</b> Exercício 1: Cartões-postais e participação eleitoral</a></li>
<li class="chapter" data-level="4.10.2" data-path="11-Synth.html"><a href="#exerc%C3%ADcio-2-an%C3%BAncios-de-tv-e-participa%C3%A7%C3%A3o-eleitoral"><i class="fa fa-check"></i><b>4.10.2</b> Exercício 2: Anúncios de TV e participação eleitoral</a></li>
<li class="chapter" data-level="4.10.3" data-path="11-Synth.html"><a href="#exerc%C3%ADcio-3-exclus%C3%A3o-de-participantes-em-experimentos-de-survey"><i class="fa fa-check"></i><b>4.10.3</b> Exercício 3: Exclusão de participantes em experimentos de survey</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html"><i class="fa fa-check"></i><b>5</b> Experimentos de Survey</a>
<ul>
<li class="chapter" data-level="5.1" data-path="11-Synth.html"><a href="#introdu%C3%A7%C3%A3o-3"><i class="fa fa-check"></i><b>5.1</b> Introdução</a></li>
<li class="chapter" data-level="5.2" data-path="11-Synth.html"><a href="#origem-hist%C3%B3ria-e-evolu%C3%A7%C3%A3o-dos-experimentos-de-survey"><i class="fa fa-check"></i><b>5.2</b> Origem, história e evolução dos experimentos de survey</a></li>
<li class="chapter" data-level="5.3" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html#usos-de-experimentos-de-survey"><i class="fa fa-check"></i><b>5.3</b> Usos de experimentos de survey</a></li>
<li class="chapter" data-level="5.4" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html#metodologia-de-survey"><i class="fa fa-check"></i><b>5.4</b> Metodologia de survey</a></li>
<li class="chapter" data-level="5.5" data-path="11-Synth.html"><a href="#mensura%C3%A7%C3%A3o-e-temas-sens%C3%ADveis"><i class="fa fa-check"></i><b>5.5</b> Mensuração e temas sensíveis</a></li>
<li class="chapter" data-level="5.6" data-path="11-Synth.html"><a href="#identifica%C3%A7%C3%A3o-causal"><i class="fa fa-check"></i><b>5.6</b> Identificação causal</a></li>
<li class="chapter" data-level="5.7" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html#tipos-de-experimentos-de-survey"><i class="fa fa-check"></i><b>5.7</b> Tipos de experimentos de survey</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html#priming"><i class="fa fa-check"></i><b>5.7.1</b> Priming</a></li>
<li class="chapter" data-level="5.7.2" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html#framing"><i class="fa fa-check"></i><b>5.7.2</b> Framing</a></li>
<li class="chapter" data-level="5.7.3" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html#endorsement-experiments"><i class="fa fa-check"></i><b>5.7.3</b> Endorsement experiments</a></li>
<li class="chapter" data-level="5.7.4" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html#list-experiments"><i class="fa fa-check"></i><b>5.7.4</b> List experiments</a></li>
<li class="chapter" data-level="5.7.5" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html#conjoint-experiments"><i class="fa fa-check"></i><b>5.7.5</b> Conjoint experiments</a></li>
<li class="chapter" data-level="5.7.6" data-path="experimentos-de-survey.html"><a href="experimentos-de-survey.html#experimentos-naturais-e-quasi-experimentos-em-surveys"><i class="fa fa-check"></i><b>5.7.6</b> Experimentos naturais e quasi-experimentos em surveys</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html"><i class="fa fa-check"></i><b>6</b> Propensity Score e Matching</a>
<ul>
<li class="chapter" data-level="6.1" data-path="11-Synth.html"><a href="#introdu%C3%A7%C3%A3o-4"><i class="fa fa-check"></i><b>6.1</b> Introdução</a></li>
<li class="chapter" data-level="6.2" data-path="11-Synth.html"><a href="#suposi%C3%A7%C3%B5es-de-identifica%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>6.2</b> Suposições de identificação</a></li>
<li class="chapter" data-level="6.3" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html#propensity-score"><i class="fa fa-check"></i><b>6.3</b> Propensity Score</a></li>
<li class="chapter" data-level="6.4" data-path="11-Synth.html"><a href="#pondera%C3%A7%C3%A3o-por-probabilidade-inversa-ipw"><i class="fa fa-check"></i><b>6.4</b> Ponderação por Probabilidade Inversa (IPW)</a></li>
<li class="chapter" data-level="6.5" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html#matching"><i class="fa fa-check"></i><b>6.5</b> Matching</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="11-Synth.html"><a href="#intui%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>6.5.1</b> Intuição</a></li>
<li class="chapter" data-level="6.5.2" data-path="11-Synth.html"><a href="#matching-como-imputa%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>6.5.2</b> Matching como imputação</a></li>
<li class="chapter" data-level="6.5.3" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html#matching-exato"><i class="fa fa-check"></i><b>6.5.3</b> Matching exato</a></li>
<li class="chapter" data-level="6.5.4" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html#matching-aproximado"><i class="fa fa-check"></i><b>6.5.4</b> Matching aproximado</a></li>
<li class="chapter" data-level="6.5.5" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html#estimando-1"><i class="fa fa-check"></i><b>6.5.5</b> Estimando</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="11-Synth.html"><a href="#aplica%C3%A7%C3%A3o-o-dataset-lalonde"><i class="fa fa-check"></i><b>6.6</b> Aplicação: o dataset LaLonde</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="11-Synth.html"><a href="#diferen%C3%A7a-bruta"><i class="fa fa-check"></i><b>6.6.1</b> Diferença bruta</a></li>
<li class="chapter" data-level="6.6.2" data-path="11-Synth.html"><a href="#balanceamento-pr%C3%A9-matching"><i class="fa fa-check"></i><b>6.6.2</b> Balanceamento pré-matching</a></li>
<li class="chapter" data-level="6.6.3" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html#nearest-neighbor-matching"><i class="fa fa-check"></i><b>6.6.3</b> Nearest-neighbor matching</a></li>
<li class="chapter" data-level="6.6.4" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html#full-matching"><i class="fa fa-check"></i><b>6.6.4</b> Full matching</a></li>
<li class="chapter" data-level="6.6.5" data-path="11-Synth.html"><a href="#estima%C3%A7%C3%A3o-do-att"><i class="fa fa-check"></i><b>6.6.5</b> Estimação do ATT</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="11-Synth.html"><a href="#recomenda%C3%A7%C3%B5es-pr%C3%A1ticas-sobre-matching"><i class="fa fa-check"></i><b>6.7</b> Recomendações Práticas sobre Matching</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="11-Synth.html"><a href="#avalia%C3%A7%C3%A3o-do-matching-feito"><i class="fa fa-check"></i><b>6.7.1</b> Avaliação do matching feito</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="11-Synth.html"><a href="#m%C3%A9todos-modernos-de-matching"><i class="fa fa-check"></i><b>6.8</b> Métodos modernos de matching</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html#coarsened-exact-matching-cem"><i class="fa fa-check"></i><b>6.8.1</b> Coarsened Exact Matching (CEM)</a></li>
<li class="chapter" data-level="6.8.2" data-path="propensity-score-e-matching.html"><a href="propensity-score-e-matching.html#entropy-balancing"><i class="fa fa-check"></i><b>6.8.2</b> Entropy Balancing</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="11-Synth.html"><a href="#an%C3%A1lise-de-sensibilidade-rosenbaum-bounds"><i class="fa fa-check"></i><b>6.9</b> Análise de sensibilidade: Rosenbaum Bounds</a></li>
<li class="chapter" data-level="6.10" data-path="11-Synth.html"><a href="#matching-e-diferen%C3%A7a-em-diferen%C3%A7as"><i class="fa fa-check"></i><b>6.10</b> Matching e Diferença em Diferenças</a></li>
<li class="chapter" data-level="6.11" data-path="11-Synth.html"><a href="#conclus%C3%A3o"><i class="fa fa-check"></i><b>6.11</b> Conclusão</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="11-Synth.html"><a href="#vari%C3%A1veis-instrumentais"><i class="fa fa-check"></i><b>7</b> Variáveis Instrumentais</a>
<ul>
<li class="chapter" data-level="7.1" data-path="11-Synth.html"><a href="#introdu%C3%A7%C3%A3o-5"><i class="fa fa-check"></i><b>7.1</b> Introdução</a></li>
<li class="chapter" data-level="7.2" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html"><i class="fa fa-check"></i><b>7.2</b> IV com modelo estrutural</a></li>
<li class="chapter" data-level="7.3" data-path="11-Synth.html"><a href="#mqo-em-2-est%C3%A1gios"><i class="fa fa-check"></i><b>7.3</b> MQO em 2 Estágios</a></li>
<li class="chapter" data-level="7.4" data-path="11-Synth.html"><a href="#efeito-heterog%C3%AAneo"><i class="fa fa-check"></i><b>7.4</b> Efeito heterogêneo</a></li>
<li class="chapter" data-level="7.5" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html#tipologia-de-unidades"><i class="fa fa-check"></i><b>7.5</b> Tipologia de unidades</a></li>
<li class="chapter" data-level="7.6" data-path="11-Synth.html"><a href="#suposi%C3%A7%C3%B5es-para-o-late"><i class="fa fa-check"></i><b>7.6</b> Suposições para o LATE</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html#sutva"><i class="fa fa-check"></i><b>7.6.1</b> SUTVA</a></li>
<li class="chapter" data-level="7.6.2" data-path="11-Synth.html"><a href="#independ%C3%AAncia"><i class="fa fa-check"></i><b>7.6.2</b> Independência</a></li>
<li class="chapter" data-level="7.6.3" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html#restricao-de-exclusao"><i class="fa fa-check"></i><b>7.6.3</b> Restrição de Exclusão</a></li>
<li class="chapter" data-level="7.6.4" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html#monotonicidade"><i class="fa fa-check"></i><b>7.6.4</b> Monotonicidade</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="11-Synth.html"><a href="#identifica%C3%A7%C3%A3o-do-late"><i class="fa fa-check"></i><b>7.7</b> Identificação do LATE</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="11-Synth.html"><a href="#passo-1-decomposi%C3%A7%C3%A3o-por-tipo"><i class="fa fa-check"></i><b>7.7.1</b> Passo 1: decomposição por tipo</a></li>
<li class="chapter" data-level="7.7.2" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html#passo-2-identificar-ptextcomplier"><i class="fa fa-check"></i><b>7.7.2</b> Passo 2: identificar <span class="math inline">\(P(\text{complier})\)</span></a></li>
<li class="chapter" data-level="7.7.3" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html#passo-3-isolar-o-late"><i class="fa fa-check"></i><b>7.7.3</b> Passo 3: isolar o LATE</a></li>
<li class="chapter" data-level="7.7.4" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html#localidade-do-late"><i class="fa fa-check"></i><b>7.7.4</b> Localidade do LATE</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="11-Synth.html"><a href="#estima%C3%A7%C3%A3o-e-for%C3%A7a-do-instrumento"><i class="fa fa-check"></i><b>7.8</b> Estimação e força do instrumento</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="11-Synth.html"><a href="#deriva%C3%A7%C3%A3o-do-estimador-2sls"><i class="fa fa-check"></i><b>7.8.1</b> Derivação do estimador 2SLS</a></li>
<li class="chapter" data-level="7.8.2" data-path="11-Synth.html"><a href="#por-que-dividir-por-hatpi-%C3%A9-problem%C3%A1tico-sob-instrumento-fraco"><i class="fa fa-check"></i><b>7.8.2</b> Por que dividir por <span class="math inline">\(\hat\pi\)</span> é problemático sob instrumento fraco</a></li>
<li class="chapter" data-level="7.8.3" data-path="11-Synth.html"><a href="#receita-pr%C3%A1tica"><i class="fa fa-check"></i><b>7.8.3</b> Receita prática</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html#principais-usos-de-iv"><i class="fa fa-check"></i><b>7.9</b> Principais usos de IV</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="variáveis-instrumentais.html"><a href="variáveis-instrumentais.html#experimentos-1"><i class="fa fa-check"></i><b>7.9.1</b> Experimentos</a></li>
<li class="chapter" data-level="7.9.2" data-path="11-Synth.html"><a href="#regras-com-varia%C3%A7%C3%A3o-quasi-aleat%C3%B3ria"><i class="fa fa-check"></i><b>7.9.2</b> Regras com variação quasi-aleatória</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="11-Synth.html"><a href="#resumo-e-pr%C3%B3ximos-passos-4"><i class="fa fa-check"></i><b>7.10</b> Resumo e próximos passos</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="11-Synth.html"><a href="#desenho-de-regress%C3%A3o-descont%C3%ADnua"><i class="fa fa-check"></i><b>8</b> Desenho de Regressão Descontínua</a>
<ul>
<li class="chapter" data-level="8.1" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html"><i class="fa fa-check"></i><b>8.1</b> Roteiro da aula</a></li>
<li class="chapter" data-level="8.2" data-path="11-Synth.html"><a href="#caracter%C3%ADsticas-chave-da-rdd"><i class="fa fa-check"></i><b>8.2</b> Características-chave da RDD</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="11-Synth.html"><a href="#determina%C3%A7%C3%A3o-do-tratamento"><i class="fa fa-check"></i><b>8.2.1</b> Determinação do Tratamento</a></li>
<li class="chapter" data-level="8.2.2" data-path="11-Synth.html"><a href="#observa%C3%A7%C3%A3o-e-corte"><i class="fa fa-check"></i><b>8.2.2</b> Observação e Corte</a></li>
<li class="chapter" data-level="8.2.3" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#estimativa-dos-efeitos-do-tratamento"><i class="fa fa-check"></i><b>8.2.3</b> Estimativa dos Efeitos do Tratamento</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#fuzzy-rd-como-iv-local"><i class="fa fa-check"></i><b>8.3</b> Fuzzy RD como IV local</a></li>
<li class="chapter" data-level="8.4" data-path="11-Synth.html"><a href="#identifica%C3%A7%C3%A3o-continuidade-e-manipula%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>8.4</b> Identificação: continuidade e manipulação</a></li>
<li class="chapter" data-level="8.5" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#dois-frameworks-para-rd"><i class="fa fa-check"></i><b>8.5</b> Dois frameworks para RD</a></li>
<li class="chapter" data-level="8.6" data-path="11-Synth.html"><a href="#estima%C3%A7%C3%A3o-em-rdd"><i class="fa fa-check"></i><b>8.6</b> Estimação em RDD</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="11-Synth.html"><a href="#bandwidth-e-infer%C3%AAncia"><i class="fa fa-check"></i><b>8.6.1</b> Bandwidth e inferência</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="11-Synth.html"><a href="#regras-arbitr%C3%A1rias"><i class="fa fa-check"></i><b>8.7</b> Regras arbitrárias</a></li>
<li class="chapter" data-level="8.8" data-path="11-Synth.html"><a href="#simula%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>8.8</b> Simulação</a></li>
<li class="chapter" data-level="8.9" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#quando-o-rdd-funciona"><i class="fa fa-check"></i><b>8.9</b> Quando o RDD funciona?</a></li>
<li class="chapter" data-level="8.10" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#dados-brutos-versus-bins"><i class="fa fa-check"></i><b>8.10</b> Dados brutos versus bins</a></li>
<li class="chapter" data-level="8.11" data-path="11-Synth.html"><a href="#testes-de-permuta%C3%A7%C3%A3o-para-balanceamento"><i class="fa fa-check"></i><b>8.11</b> Testes de permutação para balanceamento</a></li>
<li class="chapter" data-level="8.12" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#teste-de-mccrary-e-densidade"><i class="fa fa-check"></i><b>8.12</b> Teste de McCrary e densidade</a></li>
<li class="chapter" data-level="8.13" data-path="11-Synth.html"><a href="#robustez-e-infer%C3%AAncia-em-r"><i class="fa fa-check"></i><b>8.13</b> Robustez e inferência em R</a>
<ul>
<li class="chapter" data-level="8.13.1" data-path="11-Synth.html"><a href="#covari%C3%A1veis-em-rd"><i class="fa fa-check"></i><b>8.13.1</b> Covariáveis em RD</a></li>
<li class="chapter" data-level="8.13.2" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#fuzzy-rd-em-r"><i class="fa fa-check"></i><b>8.13.2</b> Fuzzy RD em R</a></li>
</ul></li>
<li class="chapter" data-level="8.14" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#testes-placebo"><i class="fa fa-check"></i><b>8.14</b> Testes placebo</a></li>
<li class="chapter" data-level="8.15" data-path="11-Synth.html"><a href="#extens%C3%B5es-e-casos-dif%C3%ADceis"><i class="fa fa-check"></i><b>8.15</b> Extensões e casos difíceis</a></li>
<li class="chapter" data-level="8.16" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#pcrd"><i class="fa fa-check"></i><b>8.16</b> PCRD</a></li>
<li class="chapter" data-level="8.17" data-path="desenho-de-regressão-descontínua.html"><a href="desenho-de-regressão-descontínua.html#checklist-para-um-paper-de-rdd"><i class="fa fa-check"></i><b>8.17</b> Checklist para um paper de RDD</a></li>
<li class="chapter" data-level="8.18" data-path="11-Synth.html"><a href="#refer%C3%AAncias-1"><i class="fa fa-check"></i><b>8.18</b> Referências</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="11-Synth.html"><a href="#diferen%C3%A7a-em-diferen%C3%A7as"><i class="fa fa-check"></i><b>9</b> Diferença em Diferenças</a>
<ul>
<li class="chapter" data-level="9.1" data-path="11-Synth.html"><a href="#motiva%C3%A7%C3%A3o-por-que-did"><i class="fa fa-check"></i><b>9.1</b> Motivação: por que DiD?</a></li>
<li class="chapter" data-level="9.2" data-path="11-Synth.html"><a href="#modelo-b%C3%A1sico-22"><i class="fa fa-check"></i><b>9.2</b> Modelo básico 2×2</a></li>
<li class="chapter" data-level="9.3" data-path="11-Synth.html"><a href="#pressupostos-de-identifica%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>9.3</b> Pressupostos de identificação</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="11-Synth.html"><a href="#tend%C3%AAncias-paralelas"><i class="fa fa-check"></i><b>9.3.1</b> Tendências paralelas</a></li>
<li class="chapter" data-level="9.3.2" data-path="11-Synth.html"><a href="#tend%C3%AAncias-paralelas-em-qual-escala"><i class="fa fa-check"></i><b>9.3.2</b> Tendências paralelas em qual escala?</a></li>
<li class="chapter" data-level="9.3.3" data-path="11-Synth.html"><a href="#equival%C3%AAncia-entre-pt-e-twfe"><i class="fa fa-check"></i><b>9.3.3</b> Equivalência entre PT e TWFE</a></li>
<li class="chapter" data-level="9.3.4" data-path="11-Synth.html"><a href="#tend%C3%AAncias-paralelas-condicionais-e-covari%C3%A1veis"><i class="fa fa-check"></i><b>9.3.4</b> Tendências paralelas condicionais e covariáveis</a></li>
<li class="chapter" data-level="9.3.5" data-path="11-Synth.html"><a href="#n%C3%A3o-antecipa%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>9.3.5</b> Não-antecipação</a></li>
<li class="chapter" data-level="9.3.6" data-path="11-Synth.html"><a href="#spillovers-e-n%C3%ADvel-de-atribui%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>9.3.6</b> Spillovers e nível de atribuição</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="11-Synth.html"><a href="#estima%C3%A7%C3%A3o-por-twfe"><i class="fa fa-check"></i><b>9.4</b> Estimação por TWFE</a></li>
<li class="chapter" data-level="9.5" data-path="11-Synth.html"><a href="#infer%C3%AAncia-em-did"><i class="fa fa-check"></i><b>9.5</b> Inferência em DiD</a></li>
<li class="chapter" data-level="9.6" data-path="11-Synth.html"><a href="#aplica%C3%A7%C3%A3o-1-obra-transparente"><i class="fa fa-check"></i><b>9.6</b> Aplicação 1: Obra Transparente</a></li>
<li class="chapter" data-level="9.7" data-path="11-Synth.html"><a href="#did-din%C3%A2mico-e-event-study"><i class="fa fa-check"></i><b>9.7</b> DiD dinâmico e event study</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="11-Synth.html"><a href="#infer%C3%AAncia-na-aplica%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>9.7.1</b> Inferência na aplicação</a></li>
<li class="chapter" data-level="9.7.2" data-path="11-Synth.html"><a href="#contamina%C3%A7%C3%A3o-em-event-studies-escalonados"><i class="fa fa-check"></i><b>9.7.2</b> Contaminação em event studies escalonados</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html"><i class="fa fa-check"></i><b>9.8</b> O problema do TWFE com tratamento escalonado</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#o-que-pode-dar-errado"><i class="fa fa-check"></i><b>9.8.1</b> O que pode dar errado</a></li>
<li class="chapter" data-level="9.8.2" data-path="11-Synth.html"><a href="#decomposi%C3%A7%C3%A3o-de-goodman-bacon-simula%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>9.8.2</b> Decomposição de Goodman-Bacon — simulação</a></li>
<li class="chapter" data-level="9.8.3" data-path="11-Synth.html"><a href="#conex%C3%A3o-com-fwl-e-gardner"><i class="fa fa-check"></i><b>9.8.3</b> Conexão com FWL e Gardner</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#estimadores-modernos"><i class="fa fa-check"></i><b>9.9</b> Estimadores modernos</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#callaway-santanna"><i class="fa fa-check"></i><b>9.9.1</b> Callaway &amp; Sant’Anna</a></li>
<li class="chapter" data-level="9.9.2" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#sun-abraham"><i class="fa fa-check"></i><b>9.9.2</b> Sun &amp; Abraham</a></li>
<li class="chapter" data-level="9.9.3" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#gardner-did2s"><i class="fa fa-check"></i><b>9.9.3</b> Gardner / did2s</a></li>
<li class="chapter" data-level="9.9.4" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#borusyak-jaravel-spiess"><i class="fa fa-check"></i><b>9.9.4</b> Borusyak, Jaravel &amp; Spiess</a></li>
<li class="chapter" data-level="9.9.5" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#tabela-comparativa"><i class="fa fa-check"></i><b>9.9.5</b> Tabela comparativa</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="11-Synth.html"><a href="#testando-tend%C3%AAncias-paralelas-e-an%C3%A1lise-de-sensibilidade"><i class="fa fa-check"></i><b>9.10</b> Testando tendências paralelas e análise de sensibilidade</a>
<ul>
<li class="chapter" data-level="9.10.1" data-path="11-Synth.html"><a href="#pr%C3%A9-tend%C3%AAncias-e-o-aviso-de-roth"><i class="fa fa-check"></i><b>9.10.1</b> Pré-tendências e o aviso de Roth</a></li>
<li class="chapter" data-level="9.10.2" data-path="11-Synth.html"><a href="#honestdid-an%C3%A1lise-de-sensibilidade"><i class="fa fa-check"></i><b>9.10.2</b> HonestDiD: análise de sensibilidade</a></li>
</ul></li>
<li class="chapter" data-level="9.11" data-path="11-Synth.html"><a href="#aplica%C3%A7%C3%A3o-2-enchente-do-elbe"><i class="fa fa-check"></i><b>9.11</b> Aplicação 2: Enchente do Elbe</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#contexto"><i class="fa fa-check"></i><b>9.11.1</b> Contexto</a></li>
<li class="chapter" data-level="9.11.2" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#dados-e-desenho-do-paper"><i class="fa fa-check"></i><b>9.11.2</b> Dados e desenho do paper</a></li>
<li class="chapter" data-level="9.11.3" data-path="11-Synth.html"><a href="#modelo-est%C3%A1tico-versus-modelo-din%C3%A2mico"><i class="fa fa-check"></i><b>9.11.3</b> Modelo estático versus modelo dinâmico</a></li>
</ul></li>
<li class="chapter" data-level="9.12" data-path="11-Synth.html"><a href="#extens%C3%B5es-e-escolhas-de-desenho"><i class="fa fa-check"></i><b>9.12</b> Extensões e escolhas de desenho</a>
<ul>
<li class="chapter" data-level="9.12.1" data-path="11-Synth.html"><a href="#diferen%C3%A7as-triplas"><i class="fa fa-check"></i><b>9.12.1</b> Diferenças triplas</a></li>
<li class="chapter" data-level="9.12.2" data-path="11-Synth.html"><a href="#tratamento-cont%C3%ADnuo-m%C3%BAltiplo-ou-revers%C3%ADvel"><i class="fa fa-check"></i><b>9.12.2</b> Tratamento contínuo, múltiplo ou reversível</a></li>
<li class="chapter" data-level="9.12.3" data-path="11-Synth.html"><a href="#ado%C3%A7%C3%A3o-aleat%C3%B3ria-no-tempo"><i class="fa fa-check"></i><b>9.12.3</b> Adoção aleatória no tempo</a></li>
<li class="chapter" data-level="9.12.4" data-path="11-Synth.html"><a href="#did-versus-vari%C3%A1vel-dependente-defasada"><i class="fa fa-check"></i><b>9.12.4</b> DiD versus variável dependente defasada</a></li>
<li class="chapter" data-level="9.12.5" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#checklist-para-aplicar-did"><i class="fa fa-check"></i><b>9.12.5</b> Checklist para aplicar DiD</a></li>
</ul></li>
<li class="chapter" data-level="9.13" data-path="11-Synth.html"><a href="#exerc%C3%ADcios-sugeridos"><i class="fa fa-check"></i><b>9.13</b> Exercícios sugeridos</a></li>
<li class="chapter" data-level="9.14" data-path="diferença-em-diferenças.html"><a href="diferença-em-diferenças.html#resumo"><i class="fa fa-check"></i><b>9.14</b> Resumo</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html"><i class="fa fa-check"></i><b>10</b> Time-Series Cross-Section (TSCS)</a>
<ul>
<li class="chapter" data-level="10.1" data-path="11-Synth.html"><a href="#introdu%C3%A7%C3%A3o-6"><i class="fa fa-check"></i><b>10.1</b> Introdução</a></li>
<li class="chapter" data-level="10.2" data-path="11-Synth.html"><a href="#varia%C3%A7%C3%A3o-within-e-between"><i class="fa fa-check"></i><b>10.2</b> Variação within e between</a></li>
<li class="chapter" data-level="10.3" data-path="11-Synth.html"><a href="#efeitos-fixos-como-residualiza%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>10.3</b> Efeitos fixos como residualização</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#um-efeito-fixo"><i class="fa fa-check"></i><b>10.3.1</b> Um efeito fixo</a></li>
<li class="chapter" data-level="10.3.2" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#dois-efeitos-fixos"><i class="fa fa-check"></i><b>10.3.2</b> Dois efeitos fixos</a></li>
<li class="chapter" data-level="10.3.3" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#mais-de-dois-efeitos-fixos"><i class="fa fa-check"></i><b>10.3.3</b> Mais de dois efeitos fixos</a></li>
<li class="chapter" data-level="10.3.4" data-path="11-Synth.html"><a href="#tratamento-cont%C3%ADnuo"><i class="fa fa-check"></i><b>10.3.4</b> Tratamento contínuo</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#ovb-e-efeitos-fixos"><i class="fa fa-check"></i><b>10.4</b> OVB e efeitos fixos</a></li>
<li class="chapter" data-level="10.5" data-path="11-Synth.html"><a href="#efeitos-aleat%C3%B3rios-e-mundlak"><i class="fa fa-check"></i><b>10.5</b> Efeitos aleatórios e Mundlak</a></li>
<li class="chapter" data-level="10.6" data-path="11-Synth.html"><a href="#hist%C3%B3rias-de-tratamento-e-estimandos"><i class="fa fa-check"></i><b>10.6</b> Histórias de tratamento e estimandos</a></li>
<li class="chapter" data-level="10.7" data-path="11-Synth.html"><a href="#quatro-pressupostos-de-identifica%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>10.7</b> Quatro pressupostos de identificação</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#mapa-dos-pressupostos"><i class="fa fa-check"></i><b>10.7.1</b> Mapa dos pressupostos</a></li>
<li class="chapter" data-level="10.7.2" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#detalhamento-dos-pressupostos"><i class="fa fa-check"></i><b>10.7.2</b> Detalhamento dos pressupostos</a></li>
<li class="chapter" data-level="10.7.3" data-path="11-Synth.html"><a href="#tend%C3%AAncias-paralelas-1"><i class="fa fa-check"></i><b>10.7.3</b> Tendências paralelas</a></li>
<li class="chapter" data-level="10.7.4" data-path="11-Synth.html"><a href="#randomiza%C3%A7%C3%A3o-no-baseline"><i class="fa fa-check"></i><b>10.7.4</b> Randomização no baseline</a></li>
<li class="chapter" data-level="10.7.5" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#exogeneidade-estrita"><i class="fa fa-check"></i><b>10.7.5</b> Exogeneidade estrita</a></li>
<li class="chapter" data-level="10.7.6" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#ignorabilidade-sequencial"><i class="fa fa-check"></i><b>10.7.6</b> Ignorabilidade sequencial</a></li>
<li class="chapter" data-level="10.7.7" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#twfe-fe-e-re-nessa-linguagem"><i class="fa fa-check"></i><b>10.7.7</b> TWFE, FE e RE nessa linguagem</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="11-Synth.html"><a href="#modelos-din%C3%A2micos-e-feedback"><i class="fa fa-check"></i><b>10.8</b> Modelos dinâmicos e feedback</a></li>
<li class="chapter" data-level="10.9" data-path="11-Synth.html"><a href="#suposi%C3%A7%C3%B5es-para-infer%C3%AAncia"><i class="fa fa-check"></i><b>10.9</b> Suposições para inferência</a>
<ul>
<li class="chapter" data-level="10.9.1" data-path="11-Synth.html"><a href="#correla%C3%A7%C3%A3o-serial"><i class="fa fa-check"></i><b>10.9.1</b> Correlação serial</a></li>
<li class="chapter" data-level="10.9.2" data-path="11-Synth.html"><a href="#raiz-unit%C3%A1ria"><i class="fa fa-check"></i><b>10.9.2</b> Raiz unitária</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="time-series-cross-section-tscs.html"><a href="time-series-cross-section-tscs.html#resumo-1"><i class="fa fa-check"></i><b>10.10</b> Resumo</a></li>
<li class="chapter" data-level="10.11" data-path="11-Synth.html"><a href="#refer%C3%AAncias-2"><i class="fa fa-check"></i><b>10.11</b> Referências</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="11-Synth.html"><a href="#interfer%C3%AAncia-spillover-e-din%C3%A2mica"><i class="fa fa-check"></i><b>11</b> Interferência, spillover e dinâmica</a>
<ul>
<li class="chapter" data-level="11.1" data-path="11-Synth.html"><a href="#suposi%C3%A7%C3%B5es-simplificadoras"><i class="fa fa-check"></i><b>11.1</b> Suposições simplificadoras</a></li>
<li class="chapter" data-level="11.2" data-path="11-Synth.html"><a href="#po-com-tratamento-de-m%C3%BAltiplos-valores-multi-valued"><i class="fa fa-check"></i><b>11.2</b> PO com tratamento de múltiplos valores (multi-valued)</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="interferência-spillover-e-dinâmica.html"><a href="interferência-spillover-e-dinâmica.html"><i class="fa fa-check"></i><b>11.2.1</b> Multi-valued discreto</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="11-Synth.html"><a href="#din%C3%A2mica"><i class="fa fa-check"></i><b>11.3</b> Dinâmica</a></li>
<li class="chapter" data-level="11.4" data-path="11-Synth.html"><a href="#interfer%C3%AAncia"><i class="fa fa-check"></i><b>11.4</b> Interferência</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="11-Synth.html"><a href="#controle-sint%C3%A9tico-e-estima%C3%A7%C3%A3o-contrafactual"><i class="fa fa-check"></i><b>12</b> Controle Sintético e Estimação Contrafactual</a>
<ul>
<li class="chapter" data-level="12.1" data-path="11-Synth.html"><a href="#motiva%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>12.1</b> Motivação</a></li>
<li class="chapter" data-level="12.2" data-path="11-Synth.html"><a href="#controle-sint%C3%A9tico-cl%C3%A1ssico"><i class="fa fa-check"></i><b>12.2</b> Controle Sintético clássico</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="11-Synth.html"><a href="#regress%C3%A3o-como-primeira-tentativa-de-contrafactual"><i class="fa fa-check"></i><b>12.2.1</b> Regressão como primeira tentativa de contrafactual</a></li>
<li class="chapter" data-level="12.2.2" data-path="11-Synth.html"><a href="#o-scm-como-restri%C3%A7%C3%A3o-disciplinadora"><i class="fa fa-check"></i><b>12.2.2</b> O SCM como restrição disciplinadora</a></li>
<li class="chapter" data-level="12.2.3" data-path="11-Synth.html"><a href="#formaliza%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>12.2.3</b> Formalização</a></li>
<li class="chapter" data-level="12.2.4" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html"><i class="fa fa-check"></i><b>12.2.4</b> Como a literatura se move a partir do SCM</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="11-Synth.html"><a href="#implementa%C3%A7%C3%A3o-do-scm-no-r"><i class="fa fa-check"></i><b>12.3</b> Implementação do SCM no R</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="11-Synth.html"><a href="#infer%C3%AAncia-por-placebo"><i class="fa fa-check"></i><b>12.3.1</b> Inferência por placebo</a></li>
<li class="chapter" data-level="12.3.2" data-path="11-Synth.html"><a href="#diagn%C3%B3sticos-de-robustez-do-scm"><i class="fa fa-check"></i><b>12.3.2</b> Diagnósticos de robustez do SCM</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#do-scm-aos-modelos-de-fatores"><i class="fa fa-check"></i><b>12.4</b> Do SCM aos modelos de fatores</a></li>
<li class="chapter" data-level="12.5" data-path="11-Synth.html"><a href="#framework-de-estima%C3%A7%C3%A3o-contrafactual"><i class="fa fa-check"></i><b>12.5</b> Framework de estimação contrafactual</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#setup"><i class="fa fa-check"></i><b>12.5.1</b> Setup</a></li>
<li class="chapter" data-level="12.5.2" data-path="11-Synth.html"><a href="#estrat%C3%A9gia-de-estima%C3%A7%C3%A3o-em-quatro-passos"><i class="fa fa-check"></i><b>12.5.2</b> Estratégia de estimação em quatro passos</a></li>
<li class="chapter" data-level="12.5.3" data-path="11-Synth.html"><a href="#suposi%C3%A7%C3%B5es-de-identifica%C3%A7%C3%A3o-1"><i class="fa fa-check"></i><b>12.5.3</b> Suposições de identificação</a></li>
<li class="chapter" data-level="12.5.4" data-path="11-Synth.html"><a href="#conex%C3%A3o-com-did"><i class="fa fa-check"></i><b>12.5.4</b> Conexão com DiD</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="11-Synth.html"><a href="#tr%C3%AAs-estimadores-contrafactuais"><i class="fa fa-check"></i><b>12.6</b> Três estimadores contrafactuais</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#fect-efeitos-fixos"><i class="fa fa-check"></i><b>12.6.1</b> FEct: efeitos fixos</a></li>
<li class="chapter" data-level="12.6.2" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#ifect-fatores-interativos"><i class="fa fa-check"></i><b>12.6.2</b> IFEct: fatores interativos</a></li>
<li class="chapter" data-level="12.6.3" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#mc-matrix-completion"><i class="fa fa-check"></i><b>12.6.3</b> MC: Matrix Completion</a></li>
<li class="chapter" data-level="12.6.4" data-path="11-Synth.html"><a href="#demonstra%C3%A7%C3%A3o-com-dados-da-calif%C3%B3rnia"><i class="fa fa-check"></i><b>12.6.4</b> Demonstração com dados da Califórnia</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="11-Synth.html"><a href="#diagn%C3%B3sticos"><i class="fa fa-check"></i><b>12.7</b> Diagnósticos</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="11-Synth.html"><a href="#efeitos-din%C3%A2micos"><i class="fa fa-check"></i><b>12.7.1</b> Efeitos dinâmicos</a></li>
<li class="chapter" data-level="12.7.2" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#placebo-test"><i class="fa fa-check"></i><b>12.7.2</b> Placebo test</a></li>
<li class="chapter" data-level="12.7.3" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#teste-de-no-carryover"><i class="fa fa-check"></i><b>12.7.3</b> Teste de no-carryover</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#synthetic-did"><i class="fa fa-check"></i><b>12.8</b> Synthetic DiD</a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="11-Synth.html"><a href="#implementa%C3%A7%C3%A3o-no-r"><i class="fa fa-check"></i><b>12.8.1</b> Implementação no R</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#trop-estimador-triplamente-robusto"><i class="fa fa-check"></i><b>12.9</b> TROP: estimador triplamente robusto</a></li>
<li class="chapter" data-level="12.10" data-path="11-Synth.html"><a href="#quando-usar-cada-m%C3%A9todo-guia-pr%C3%A1tico"><i class="fa fa-check"></i><b>12.10</b> Quando usar cada método: guia prático</a></li>
<li class="chapter" data-level="12.11" data-path="controle-sintético-e-estimação-contrafactual.html"><a href="controle-sintético-e-estimação-contrafactual.html#resumo-2"><i class="fa fa-check"></i><b>12.11</b> Resumo</a></li>
<li class="chapter" data-level="12.12" data-path="11-Synth.html"><a href="#refer%C3%AAncias-3"><i class="fa fa-check"></i><b>12.12</b> Referências</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="llms-e-outras.html"><a href="llms-e-outras.html"><i class="fa fa-check"></i><b>13</b> LLMs e outras</a>
<ul>
<li class="chapter" data-level="13.1" data-path="llms-e-outras.html"><a href="llms-e-outras.html#google-colab"><i class="fa fa-check"></i><b>13.1</b> Google Colab</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="machine-learning.html"><a href="machine-learning.html"><i class="fa fa-check"></i><b>14</b> Machine Learning</a>
<ul>
<li class="chapter" data-level="14.1" data-path="11-Synth.html"><a href="#introdu%C3%A7%C3%A3o-7"><i class="fa fa-check"></i><b>14.1</b> Introdução</a></li>
<li class="chapter" data-level="14.2" data-path="machine-learning.html"><a href="machine-learning.html#terminologia"><i class="fa fa-check"></i><b>14.2</b> Terminologia</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="machine-learning.html"><a href="machine-learning.html#lasso"><i class="fa fa-check"></i><b>14.2.1</b> LASSO</a></li>
<li class="chapter" data-level="14.2.2" data-path="machine-learning.html"><a href="machine-learning.html#double-lasso"><i class="fa fa-check"></i><b>14.2.2</b> Double Lasso</a></li>
<li class="chapter" data-level="14.2.3" data-path="11-Synth.html"><a href="#outras-solu%C3%A7%C3%B5es-ineficazes"><i class="fa fa-check"></i><b>14.2.3</b> Outras soluções ineficazes</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="machine-learning.html"><a href="machine-learning.html#dl---algoritmo"><i class="fa fa-check"></i><b>14.3</b> DL - Algoritmo</a></li>
<li class="chapter" data-level="14.4" data-path="11-Synth.html"><a href="#termos-de-intera%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>14.4</b> Termos de Interação</a></li>
<li class="chapter" data-level="14.5" data-path="11-Synth.html"><a href="#aplica%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>14.5</b> Aplicação</a></li>
<li class="chapter" data-level="14.6" data-path="machine-learning.html"><a href="machine-learning.html#dml"><i class="fa fa-check"></i><b>14.6</b> DML</a></li>
<li class="chapter" data-level="14.7" data-path="machine-learning.html"><a href="machine-learning.html#double-debiasing"><i class="fa fa-check"></i><b>14.7</b> Double Debiasing</a></li>
<li class="chapter" data-level="14.8" data-path="machine-learning.html"><a href="machine-learning.html#cross-fitting"><i class="fa fa-check"></i><b>14.8</b> Cross-fitting</a></li>
<li class="chapter" data-level="14.9" data-path="11-Synth.html"><a href="#quest%C3%B5es-pr%C3%A1ticas"><i class="fa fa-check"></i><b>14.9</b> Questões Práticas</a></li>
<li class="chapter" data-level="14.10" data-path="11-Synth.html"><a href="#resumo-e-pr%C3%B3ximos-passos-5"><i class="fa fa-check"></i><b>14.10</b> Resumo e próximos passos</a></li>
<li class="chapter" data-level="14.11" data-path="11-Synth.html"><a href="#refer%C3%AAncias-4"><i class="fa fa-check"></i><b>14.11</b> Referências</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="resumo-3.html"><a href="resumo-3.html"><i class="fa fa-check"></i><b>15</b> Resumo</a>
<ul>
<li class="chapter" data-level="15.1" data-path="resumo-3.html"><a href="resumo-3.html#matching-1"><i class="fa fa-check"></i><b>15.1</b> Matching</a></li>
<li class="chapter" data-level="15.2" data-path="resumo-3.html"><a href="resumo-3.html#iv"><i class="fa fa-check"></i><b>15.2</b> IV</a></li>
<li class="chapter" data-level="15.3" data-path="resumo-3.html"><a href="resumo-3.html#rdd"><i class="fa fa-check"></i><b>15.3</b> RDD</a></li>
<li class="chapter" data-level="15.4" data-path="resumo-3.html"><a href="resumo-3.html#did"><i class="fa fa-check"></i><b>15.4</b> DiD</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="resumo-3.html"><a href="resumo-3.html#tscs"><i class="fa fa-check"></i><b>15.4.1</b> TSCS</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="resumo-3.html"><a href="resumo-3.html#scm"><i class="fa fa-check"></i><b>15.5</b> SCM</a></li>
<li class="chapter" data-level="15.6" data-path="11-Synth.html"><a href="#did-sint%C3%A9tico"><i class="fa fa-check"></i><b>15.6</b> DiD Sintético</a></li>
<li class="chapter" data-level="15.7" data-path="resumo-3.html"><a href="resumo-3.html#double-lasso-1"><i class="fa fa-check"></i><b>15.7</b> Double LASSO</a></li>
<li class="chapter" data-level="15.8" data-path="resumo-3.html"><a href="resumo-3.html#dml-1"><i class="fa fa-check"></i><b>15.8</b> DML</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="shift-share.html"><a href="shift-share.html"><i class="fa fa-check"></i><b>16</b> Shift-share</a>
<ul>
<li class="chapter" data-level="16.1" data-path="11-Synth.html"><a href="#introdu%C3%A7%C3%A3o-8"><i class="fa fa-check"></i><b>16.1</b> Introdução</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="11-Synth.html"><a href="#aplica%C3%A7%C3%A3o-pib-por-estado-e-setor"><i class="fa fa-check"></i><b>16.1.1</b> Aplicação: PIB por estado e setor</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="11-Synth.html"><a href="#exemplos-da-pol%C3%ADtica"><i class="fa fa-check"></i><b>16.2</b> Exemplos da Política</a></li>
<li class="chapter" data-level="16.3" data-path="11-Synth.html"><a href="#varia%C3%A7%C3%A3o-temporal"><i class="fa fa-check"></i><b>16.3</b> Variação temporal</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="11-Synth.html"><a href="#aplica%C3%A7%C3%A3o-elei%C3%A7%C3%B5es-presidenciais-20142018"><i class="fa fa-check"></i><b>16.3.1</b> Aplicação: Eleições presidenciais 2014→2018</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="11-Synth.html"><a href="#o-instrumento-shift-share-como-vari%C3%A1vel-instrumental"><i class="fa fa-check"></i><b>16.4</b> O instrumento shift-share como variável instrumental</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="11-Synth.html"><a href="#constru%C3%A7%C3%A3o-formal"><i class="fa fa-check"></i><b>16.4.1</b> Construção formal</a></li>
<li class="chapter" data-level="16.4.2" data-path="shift-share.html"><a href="shift-share.html#voltando-ao-exemplo-construindo-w_ik-g_k-e-b_i-com-dados-eleitorais"><i class="fa fa-check"></i><b>16.4.2</b> Voltando ao exemplo: construindo <span class="math inline">\(w_{ik}\)</span>, <span class="math inline">\(g_k\)</span> e <span class="math inline">\(B_i\)</span> com dados eleitorais</a></li>
<li class="chapter" data-level="16.4.3" data-path="shift-share.html"><a href="shift-share.html#o-modelo-estrutural-e-o-iv"><i class="fa fa-check"></i><b>16.4.3</b> O modelo estrutural e o IV</a></li>
<li class="chapter" data-level="16.4.4" data-path="shift-share.html"><a href="shift-share.html#interpretando-o-modelo-com-o-exemplo-eleitoral"><i class="fa fa-check"></i><b>16.4.4</b> Interpretando o modelo com o exemplo eleitoral</a></li>
<li class="chapter" data-level="16.4.5" data-path="11-Synth.html"><a href="#por-que-o-instrumento-seria-v%C3%A1lido-uma-discuss%C3%A3o-intuitiva"><i class="fa fa-check"></i><b>16.4.5</b> Por que o instrumento seria válido? Uma discussão intuitiva</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="11-Synth.html"><a href="#duas-estrat%C3%A9gias-de-identifica%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>16.5</b> Duas estratégias de identificação</a>
<ul>
<li class="chapter" data-level="16.5.1" data-path="11-Synth.html"><a href="#estrat%C3%A9gia-1-exogeneidade-das-shares-gpss-2020"><i class="fa fa-check"></i><b>16.5.1</b> Estratégia 1: Exogeneidade das shares (GPSS 2020)</a></li>
<li class="chapter" data-level="16.5.2" data-path="11-Synth.html"><a href="#estrat%C3%A9gia-2-exogeneidade-dos-shifts-bhj-2022"><i class="fa fa-check"></i><b>16.5.2</b> Estratégia 2: Exogeneidade dos shifts (BHJ 2022)</a></li>
<li class="chapter" data-level="16.5.3" data-path="11-Synth.html"><a href="#resumo-das-duas-estrat%C3%A9gias"><i class="fa fa-check"></i><b>16.5.3</b> Resumo das duas estratégias</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="11-Synth.html"><a href="#o-problema-de-infer%C3%AAncia"><i class="fa fa-check"></i><b>16.6</b> O problema de inferência</a></li>
<li class="chapter" data-level="16.7" data-path="11-Synth.html"><a href="#implementa%C3%A7%C3%A3o-em-r"><i class="fa fa-check"></i><b>16.7</b> Implementação em R</a>
<ul>
<li class="chapter" data-level="16.7.1" data-path="11-Synth.html"><a href="#constru%C3%A7%C3%A3o-do-instrumento"><i class="fa fa-check"></i><b>16.7.1</b> Construção do instrumento</a></li>
<li class="chapter" data-level="16.7.2" data-path="11-Synth.html"><a href="#estima%C3%A7%C3%A3o-iv"><i class="fa fa-check"></i><b>16.7.2</b> Estimação IV</a></li>
<li class="chapter" data-level="16.7.3" data-path="11-Synth.html"><a href="#erros-padr%C3%A3o-corrigidos-pacote-shiftsharese"><i class="fa fa-check"></i><b>16.7.3</b> Erros-padrão corrigidos: pacote <code>ShiftShareSE</code></a></li>
<li class="chapter" data-level="16.7.4" data-path="11-Synth.html"><a href="#agrega%C3%A7%C3%A3o-ao-n%C3%ADvel-do-choque-pacote-ssaggregate"><i class="fa fa-check"></i><b>16.7.4</b> Agregação ao nível do choque: pacote <code>ssaggregate</code></a></li>
<li class="chapter" data-level="16.7.5" data-path="shift-share.html"><a href="shift-share.html#ecossistema-r-vs.-stata"><i class="fa fa-check"></i><b>16.7.5</b> Ecossistema R vs. Stata</a></li>
</ul></li>
<li class="chapter" data-level="16.8" data-path="11-Synth.html"><a href="#aplica%C3%A7%C3%B5es-em-ci%C3%AAncia-pol%C3%ADtica"><i class="fa fa-check"></i><b>16.8</b> Aplicações em Ciência Política</a>
<ul>
<li class="chapter" data-level="16.8.1" data-path="11-Synth.html"><a href="#com%C3%A9rcio-e-voto-nos-eua"><i class="fa fa-check"></i><b>16.8.1</b> Comércio e voto nos EUA</a></li>
<li class="chapter" data-level="16.8.2" data-path="11-Synth.html"><a href="#com%C3%A9rcio-e-nacionalismo-na-europa"><i class="fa fa-check"></i><b>16.8.2</b> Comércio e nacionalismo na Europa</a></li>
<li class="chapter" data-level="16.8.3" data-path="11-Synth.html"><a href="#valores-autorit%C3%A1rios"><i class="fa fa-check"></i><b>16.8.3</b> Valores autoritários</a></li>
<li class="chapter" data-level="16.8.4" data-path="11-Synth.html"><a href="#welfare-state-hist%C3%B3rico"><i class="fa fa-check"></i><b>16.8.4</b> Welfare state histórico</a></li>
<li class="chapter" data-level="16.8.5" data-path="11-Synth.html"><a href="#automa%C3%A7%C3%A3o-e-redistribui%C3%A7%C3%A3o"><i class="fa fa-check"></i><b>16.8.5</b> Automação e redistribuição</a></li>
<li class="chapter" data-level="16.8.6" data-path="shift-share.html"><a href="shift-share.html#brasil"><i class="fa fa-check"></i><b>16.8.6</b> Brasil</a></li>
<li class="chapter" data-level="16.8.7" data-path="11-Synth.html"><a href="#competi%C3%A7%C3%A3o-pol%C3%ADtica-e-desmatamento"><i class="fa fa-check"></i><b>16.8.7</b> Competição política e desmatamento</a></li>
</ul></li>
<li class="chapter" data-level="16.9" data-path="11-Synth.html"><a href="#aplica%C3%A7%C3%B5es-em-rela%C3%A7%C3%B5es-internacionais"><i class="fa fa-check"></i><b>16.9</b> Aplicações em Relações Internacionais</a>
<ul>
<li class="chapter" data-level="16.9.1" data-path="11-Synth.html"><a href="#com%C3%A9rcio-e-pol%C3%ADtica-externa"><i class="fa fa-check"></i><b>16.9.1</b> Comércio e política externa</a></li>
<li class="chapter" data-level="16.9.2" data-path="11-Synth.html"><a href="#comportamento-legislativo-em-pol%C3%ADtica-comercial"><i class="fa fa-check"></i><b>16.9.2</b> Comportamento legislativo em política comercial</a></li>
<li class="chapter" data-level="16.9.3" data-path="shift-share.html"><a href="shift-share.html#temas-com-potencial-inexplorado-em-ri"><i class="fa fa-check"></i><b>16.9.3</b> Temas com potencial inexplorado em RI</a></li>
</ul></li>
<li class="chapter" data-level="16.10" data-path="11-Synth.html"><a href="#refer%C3%AAncias-5"><i class="fa fa-check"></i><b>16.10</b> Referências</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso de Inferência Causal</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="controle-sintético-e-estimação-contrafactual" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Capítulo 12</span> Controle Sintético e Estimação Contrafactual<a href="#controle-sint%C3%A9tico-e-estima%C3%A7%C3%A3o-contrafactual" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Objetivos de aprendizado.</strong> Ao final deste capítulo, o leitor será capaz de:</p>
<ol style="list-style-type: decimal">
<li>Explicar como regressão e SCM imputam contrafactuais a partir dos controles, distinguindo pesos implícitos de pesos convexos explícitos.</li>
<li>Implementar o SCM no R e interpretar seus resultados (pesos, balanço de preditores, gráficos de gap).</li>
<li>Avaliar criticamente a inferência por permutação do SCM, incluindo suas limitações quando o tratamento não é aleatorizado.</li>
<li>Distinguir entre modelos aditivos (FEct/DiD) e modelos de fatores (IFEct/MC), e entender quando cada um é apropriado.</li>
<li>Explicar como o SCM motiva modelos de fatores, e por que estimar fatores diretamente pode ser mais eficiente quando há múltiplas unidades tratadas.</li>
<li>Comparar DiD, SCM, SDiD e TROP em termos de suposições, flexibilidade e robustez, e escolher o método adequado para uma aplicação concreta.</li>
</ol>
<div id="motivação" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> Motivação<a href="#motiva%C3%A7%C3%A3o" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>No capítulo 8, vimos que o DiD requer tendências paralelas: na ausência de tratamento, tratados e controles teriam evoluído de forma similar. Mas essa suposição é frequentemente violada — especialmente quando há poucas unidades tratadas (às vezes apenas uma) ou quando confundidores variam no tempo de forma heterogênea entre grupos.</p>
<p>Este capítulo apresenta uma família de métodos que compartilham a mesma lógica: <strong>imputar o contrafactual</strong> <span class="math inline">\(Y_{it}(0)\)</span> para as observações tratadas. A diferença entre eles está no <em>modelo</em> que usam para essa imputação e nas <em>restrições</em> que impõem:</p>
<ul>
<li>O <strong>Controle Sintético</strong> (SCM) constrói o contrafactual como combinação convexa de unidades não-tratadas.</li>
<li>O <strong>framework de estimação contrafactual</strong> (Liu, Wang &amp; Xu, 2024) generaliza a imputação para três estimadores — FEct, IFEct e MC — com diagnósticos formais.</li>
<li>O <strong>Synthetic DiD</strong> (Arkhangelsky et al., 2021) combina pesos de unidade (como SCM) com pesos temporais e efeitos fixos (como DiD).</li>
<li>O <strong>TROP</strong> (Athey et al., 2025) combina um modelo de fatores com pesos de unidade e pesos temporais, obtendo tripla robustez.</li>
</ul>
<p><strong>Mapa do capítulo.</strong> As seções 2–3 cobrem o SCM clássico e sua implementação no R. A seção 4 introduz o framework de estimação contrafactual. A seção 5 apresenta os três estimadores (FEct, IFEct, MC) com aplicação empírica. A seção 6 discute diagnósticos. A seção 7 apresenta o Synthetic DiD. A seção 8 introduz o TROP. A seção 9 oferece um guia prático de escolha entre métodos. A seção 10 resume o capítulo.</p>
</div>
<div id="controle-sintético-clássico" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Controle Sintético clássico<a href="#controle-sint%C3%A9tico-cl%C3%A1ssico" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O método de controle sintético foi originalmente proposto por Abadie e Gardeazabal (2003) para estimar os custos econômicos do conflito no País Basco, e posteriormente formalizado e popularizado por Abadie, Diamond e Hainmueller (2010, 2015). A intuição aparece com clareza no exemplo clássico da Proposição 99. A Califórnia aprovou em 1988 uma política ampla de controle do tabaco. Queremos estimar seu efeito sobre as vendas per capita de cigarros:</p>
<p><span class="math display">\[
\tau_t = Y_{CA,t}(1) - Y_{CA,t}(0), \quad \text{para } t &gt; 1988
\]</span></p>
<p>O termo observado é <span class="math inline">\(Y_{CA,t}(1)\)</span>, a trajetória da Califórnia após a política. O termo que falta é <span class="math inline">\(Y_{CA,t}(0)\)</span>, a trajetória que a Califórnia teria seguido sem a Proposição 99. Esse contrafactual não está nos dados. Todo o problema é construir uma estimativa crível de <span class="math inline">\(Y_{CA,t}(0)\)</span> usando os estados que não adotaram a política.</p>
<table>
<caption><span id="tab:cigarro">Tabela 12.1: </span>Primeiras observações dos dados de vendas de cigarros.</caption>
<thead>
<tr class="header">
<th align="left">state</th>
<th align="right">year</th>
<th align="right">cigsale</th>
<th align="left">california</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Rhode Island</td>
<td align="right">1970</td>
<td align="right">123.9</td>
<td align="left">FALSE</td>
</tr>
<tr class="even">
<td align="left">Tennessee</td>
<td align="right">1970</td>
<td align="right">99.8</td>
<td align="left">FALSE</td>
</tr>
<tr class="odd">
<td align="left">Indiana</td>
<td align="right">1970</td>
<td align="right">134.6</td>
<td align="left">FALSE</td>
</tr>
<tr class="even">
<td align="left">Nevada</td>
<td align="right">1970</td>
<td align="right">189.5</td>
<td align="left">FALSE</td>
</tr>
<tr class="odd">
<td align="left">Louisiana</td>
<td align="right">1970</td>
<td align="right">115.9</td>
<td align="left">FALSE</td>
</tr>
<tr class="even">
<td align="left">Oklahoma</td>
<td align="right">1970</td>
<td align="right">108.4</td>
<td align="left">FALSE</td>
</tr>
</tbody>
</table>
<div class="figure"><span style="display:block;" id="fig:cigarro"></span>
<img src="bookdownproj_files/figure-html/cigarro-1.png" alt="Vendas per capita de cigarros na Califórnia e nos demais estados. A linha vertical marca a aprovação da Proposição 99 em 1988." width="672" />
<p class="caption">
Figura 12.1: Vendas per capita de cigarros na Califórnia e nos demais estados. A linha vertical marca a aprovação da Proposição 99 em 1988.
</p>
</div>
<p>A média simples dos demais estados não é um bom contrafactual. Os controles diferem da Califórnia em nível e tendência antes de 1988. Uma primeira saída natural é usar regressão: estimar, entre os estados não tratados, uma relação entre características pré-tratamento e o resultado futuro, e depois aplicar essa relação à Califórnia.</p>
<div id="regressão-como-primeira-tentativa-de-contrafactual" class="section level3 hasAnchor" number="12.2.1">
<h3><span class="header-section-number">12.2.1</span> Regressão como primeira tentativa de contrafactual<a href="#regress%C3%A3o-como-primeira-tentativa-de-contrafactual" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Considere uma regressão estimada apenas no <em>donor pool</em>. Para cada estado de controle, construímos um vetor de preditores pré-tratamento, incluindo valores defasados de vendas de cigarros e covariáveis como renda, preço relativo e composição etária. Para fixar a ideia, suponha que queremos prever as vendas per capita em 2000:</p>
<p><span class="math display">\[
\text{cigsale}_{j,2000}
= \alpha
+ \beta_{1970}\text{cigsale}_{j,1970}
+ \cdots
+ \beta_{1988}\text{cigsale}_{j,1988}
+ Z&#39;_j\gamma
+ u_j,
\quad j \in co.
\]</span></p>
<p>Aqui, <span class="math inline">\(co\)</span> denota o conjunto de estados de controle.</p>
<p>Depois de estimar o modelo nos controles, inserimos os preditores da Califórnia e obtemos <span class="math inline">\(\widehat{Y}_{CA,2000}(0)\)</span>. Essa operação parece diferente do SCM, mas também constrói o contrafactual como uma combinação linear dos estados de controle.</p>
<p>Defina <span class="math inline">\(X\)</span> como a matriz de preditores dos estados de controle, incluindo a constante, <span class="math inline">\(y\)</span> como o vetor de resultados dos controles em 2000, e <span class="math inline">\(x_{CA}\)</span> como o vetor de preditores da Califórnia. A regressão produz:</p>
<p><span class="math display">\[
\widehat{\beta} = (X&#39;X)^{-1}X&#39;y.
\]</span></p>
<p>A previsão para a Califórnia é:</p>
<p><span class="math display">\[
\widehat{Y}_{CA,2000}(0)
= x_{CA}&#39;\widehat{\beta}
= x_{CA}&#39;(X&#39;X)^{-1}X&#39;y.
\]</span></p>
<p>Agrupando os termos que multiplicam <span class="math inline">\(y\)</span>, temos:</p>
<p><span class="math display">\[
h_{CA} = x_{CA}&#39;(X&#39;X)^{-1}X&#39;,
\]</span></p>
<p>e portanto:</p>
<p><span class="math display">\[
\widehat{Y}_{CA,2000}(0)
= h_1Y_{1,2000} + h_2Y_{2,2000} + \cdots + h_JY_{J,2000}.
\]</span></p>
<p>O vetor <span class="math inline">\(h_{CA}\)</span> é uma linha <em>out-of-sample</em> análoga à <em>hat matrix</em>. Cada elemento de <span class="math inline">\(h_{CA}\)</span> é o peso de um estado de controle no contrafactual por regressão. Com intercepto, esses pesos somam 1. A diferença é que a regressão não exige que sejam positivos, menores que 1 ou concentrados em poucos doadores.</p>
<table>
<caption><span id="tab:tabela-pesos-regressao-scm">Tabela 12.2: </span>Resumo dos pesos usados pelo SCM e dos pesos implícitos da regressão no exemplo da Califórnia.</caption>
<colgroup>
<col width="15%" />
<col width="16%" />
<col width="12%" />
<col width="12%" />
<col width="17%" />
<col width="16%" />
<col width="9%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Método</th>
<th align="right">Soma dos pesos</th>
<th align="right">Peso mínimo</th>
<th align="right">Peso máximo</th>
<th align="right">Pesos negativos</th>
<th align="right">Pesos efetivos</th>
<th align="right">Norma L1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">SCM</td>
<td align="right">1</td>
<td align="right">0.000</td>
<td align="right">0.342</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">1.00</td>
</tr>
<tr class="even">
<td align="left">Regressão OLS</td>
<td align="right">1</td>
<td align="right">-0.325</td>
<td align="right">0.493</td>
<td align="right">17</td>
<td align="right">38</td>
<td align="right">3.96</td>
</tr>
</tbody>
</table>
<p>A tabela mostra o ponto de Abadie e L’Hour (2021). A regressão também usa os controles como uma combinação ponderada. No exemplo, os pesos implícitos da OLS somam 1, mas 17 são negativos e todos os 38 estados entram com peso efetivo. O SCM também soma 1, mas não tem pesos negativos e concentra peso em cinco doadores. Entre os maiores pesos em valor absoluto da regressão estão Connecticut, Montana e Utah com pesos positivos, e Mississippi e Oklahoma com pesos negativos.</p>
<div class="figure"><span style="display:block;" id="fig:figura-contrafactual-scm-regressao"></span>
<img src="outputs/scm_vs_regressao_prop99/figura_2_contrafactual_scm_vs_regressao.png" alt="Califórnia observada, contrafactual por regressão e controle sintético. A linha vertical marca a Proposição 99 em 1988." width="95%" />
<p class="caption">
Figura 12.2: Califórnia observada, contrafactual por regressão e controle sintético. A linha vertical marca a Proposição 99 em 1988.
</p>
</div>
<p>Em 2000, a Califórnia observada vendeu 41.6 maços per capita. A regressão prevê 53 e o SCM prevê 67.2. A comparação não prova que um estimador domina o outro. Ela mostra que contrafactuais com bom ajuste pré-tratamento podem ser produzidos por objetos substantivamente diferentes.</p>
<p>Na figura, a série por regressão usa o mesmo vetor <span class="math inline">\(h_{CA}\)</span> para todos os anos. Isso corresponde a manter o mesmo conjunto de preditores e mudar apenas o resultado a ser previsto. Como esses preditores incluem muitas defasagens pré-tratamento, o bom ajuste no pré deve ser lido como diagnóstico descritivo, não como validação fora da amostra.</p>
<p>O problema não é apenas verificar se o ajuste pré-tratamento é bom. Isso vale para regressão, SCM e métodos posteriores. A pergunta mais difícil é que tipo de contrafactual gerou esse ajuste. Três riscos aparecem:</p>
<ol style="list-style-type: decimal">
<li><strong>Confundimento dinâmico.</strong> Se a Califórnia difere dos controles em fatores que afetam <span class="math inline">\(Y(0)\)</span> e esses fatores não estão nos preditores, a previsão por regressão pode errar mesmo quando o ajuste observado parece razoável.</li>
<li><strong>Extrapolação funcional.</strong> A regressão depende da forma funcional estimada nos controles. Quando a Califórnia está fora do suporte empírico dos controles, a previsão pode extrapolar além das comparações observadas.</li>
<li><strong>Baixa auditabilidade substantiva.</strong> Pesos negativos e não esparsos dificultam a interpretação. A “Califórnia da regressão” pode somar alguns estados e subtrair outros. Essa construção é legítima como álgebra, mas é difícil de defender qualitativamente como unidade comparável.</li>
</ol>
</div>
<div id="o-scm-como-restrição-disciplinadora" class="section level3 hasAnchor" number="12.2.2">
<h3><span class="header-section-number">12.2.2</span> O SCM como restrição disciplinadora<a href="#o-scm-como-restri%C3%A7%C3%A3o-disciplinadora" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O SCM parte do mesmo problema, mas restringe a classe de contrafactuais admissíveis. Em vez de deixar a regressão escolher pesos implícitos sem restrição de sinal, o SCM constrói:</p>
<p><span class="math display">\[
\hat{Y}_{CA,t}(0) = \sum_{j \in co} w_jY_{j,t}
\]</span></p>
<p>com:</p>
<p><span class="math display">\[
w_j \geq 0
\qquad \text{e} \qquad
\sum_{j \in co} w_j = 1.
\]</span></p>
<p>Essas duas restrições forçam o contrafactual a ser uma combinação convexa explícita dos controles. Geometricamente, a Califórnia sintética precisa ficar dentro do <em>convex hull</em> do <em>donor pool</em>. Isso reduz extrapolação forte: o método tenta interpolar dentro do envelope empírico dos controles, em vez de projetar livremente a partir de uma forma funcional.</p>
<p>A analogia com <em>matching</em> é útil. O SCM funciona como uma versão ponderada de <em>nearest-neighbor matching</em>: procura controles parecidos com a unidade tratada, mas não impõe pesos iguais nem fixa previamente o número de vizinhos. A diferença é que a proximidade é definida pela capacidade de reproduzir a trajetória e os preditores pré-tratamento.</p>
<p>Essa disciplina tem custo. A convexidade pode ser rígida demais quando a unidade tratada está fora do <em>convex hull</em> ou quando nenhuma combinação de controles ajusta bem o pré-tratamento. O SCM não é sempre melhor que regressão. Ele troca flexibilidade por transparência, auditabilidade e menor extrapolação.</p>
</div>
<div id="formalização" class="section level3 hasAnchor" number="12.2.3">
<h3><span class="header-section-number">12.2.3</span> Formalização<a href="#formaliza%C3%A7%C3%A3o" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suponha que temos dados para <span class="math inline">\(J+1\)</span> unidades por <span class="math inline">\(T\)</span> períodos: <span class="math inline">\(1, 2, \ldots, T_0, T_0+1, \ldots, T\)</span>. A primeira unidade (<span class="math inline">\(j=1\)</span>) é tratada a partir de <span class="math inline">\(T_0+1\)</span>. As demais <span class="math inline">\(j = 2, \ldots, J+1\)</span> formam o <em>donor pool</em>. Para cada unidade, observamos um vetor de <span class="math inline">\(k\)</span> preditores <span class="math inline">\(\mathbf{X}_j\)</span>, que pode incluir valores pré-intervenção da variável resposta.</p>
<p>Os dados podem ser organizados em blocos, onde as linhas representam períodos (pré e pós-tratamento) e as colunas representam unidades (controle e tratada):</p>
<p><span class="math display">\[
\begin{aligned}
D \;=\;
\underset{\text{linhas: períodos}}{\underbrace{
\begin{pmatrix}
\mathbf{0} &amp; \mathbf{0}  \\
\mathbf{0} &amp; \mathbf{1}
\end{pmatrix}
}}
\quad
\begin{matrix}
\leftarrow \text{pré} \\
\leftarrow \text{pós}
\end{matrix}
\qquad
Y \;=\;
\underset{\text{colunas: controle | tratada}}{\underbrace{
\begin{pmatrix}
Y_{co, pre}(0) &amp; Y_{tr, pre}(0)  \\
Y_{co, post}(0)  &amp; Y_{tr, post}(1)
\end{pmatrix}
}}
\end{aligned}
\]</span></p>
<p>O estimando é o ATT para os períodos pós-tratamento:
<span class="math display">\[
\tau_t = \mathbb{E}[Y_{it}(1) \mid D_{it}=1] - \mathbb{E}[Y_{it}(0) \mid D_{it}=1]
\]</span></p>
<p>O contrafactual é estimado como média ponderada do donor pool:
<span class="math display">\[
\hat{Y}_{tr, t}(0) = \sum_{j \in co} w_j Y_{j,t}
\]</span></p>
<p>com as restrições:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\sum_j w_j = 1\)</span> (combinação convexa)</li>
<li><span class="math inline">\(w_j \geq 0\)</span>, <span class="math inline">\(\forall j\)</span> (pesos não-negativos)</li>
</ol>
<p>Os pesos são escolhidos para que o controle sintético reproduza bem a unidade tratada antes da intervenção. O principal diagnóstico de ajuste é o RMSPE (<em>Root Mean Squared Prediction Error</em>) no período pré-tratamento:</p>
<p><span class="math display">\[
\operatorname{RMSPE}_{pre}(\mathbf{w}) =
\sqrt{
\frac{1}{T_0}
\sum_{t \leq T_0}
\left(Y_{tr,t} - \sum_{j \in co} w_j Y_{j,t}\right)^2
}.
\]</span></p>
<p>Na formulação de Abadie, Diamond e Hainmueller (2010), isso é implementado minimizando a distância entre os preditores da unidade tratada e a combinação ponderada dos controles:
<span class="math display">\[
\hat{\mathbf{W}}(V) = \arg\min_{\mathbf{W}} (\mathbf{X}_{tr} - \mathbf{X}_{co}\mathbf{W})&#39; V (\mathbf{X}_{tr} - \mathbf{X}_{co}\mathbf{W})
\]</span>
onde <span class="math inline">\(\mathbf{X}\)</span> inclui a variável dependente defasada como preditor, e <span class="math inline">\(V\)</span> é uma matriz diagonal positiva semidefinida (<span class="math inline">\(k \times k\)</span>) que atribui importância relativa a cada preditor. A escolha de <span class="math inline">\(V\)</span> é feita por uma otimização aninhada (<em>nested optimization</em>): no loop externo, <span class="math inline">\(V\)</span> é escolhida para minimizar o RMSPE no período pré-tratamento; no loop interno, dado <span class="math inline">\(V\)</span>, os pesos <span class="math inline">\(\mathbf{W}\)</span> são otimizados sob as restrições de não-negatividade e soma igual a 1. Isso significa que os resultados do SCM dependem da escolha dos preditores incluídos em <span class="math inline">\(\mathbf{X}\)</span> — tanto a seleção quanto a ponderação dos preditores afetam a solução final.</p>
<p><strong>Por que o SCM funciona?</strong> Sob um modelo linear de fatores <span class="math inline">\(Y_{it}(0) = \delta_t + \theta_t Z_i + \lambda_t \mu_i + \varepsilon_{it}\)</span>, onde <span class="math inline">\(Z_i\)</span> são covariáveis observadas, <span class="math inline">\(\mu_i\)</span> são fatores não-observados e <span class="math inline">\(\lambda_t\)</span> são cargas temporais, Abadie, Diamond e Hainmueller (2010, Proposição 1) mostram que, se existem pesos que reproduzem exatamente os preditores pré-tratamento da unidade tratada (isto é, <span class="math inline">\(\mathbf{X}_{tr} = \mathbf{X}_{co}\mathbf{W}\)</span>), então o viés do SCM desaparece quando <span class="math inline">\(T_0 \to \infty\)</span>. Intuitivamente, ao reproduzir as trajetórias pré-tratamento e as covariáveis observadas, o controle sintético também reproduz os fatores latentes não-observados — que são a fonte de viés na ausência de tendências paralelas.</p>
<p><strong>Risco de sobreajuste.</strong> Otimizar o ajuste pré-tratamento pode levar a <em>overfitting</em>, especialmente quando se incluem todos os valores defasados da variável resposta como preditores. Kaul et al. (2022) mostram que incluir todas as defasagens torna os demais preditores irrelevantes para a otimização. A recomendação prática é usar defasagens selecionadas (por exemplo, <span class="math inline">\(Y_{i,T_0}\)</span>, <span class="math inline">\(Y_{i,T_0/2}\)</span>) e médias de covariáveis, em vez de todos os resultados pré-tratamento. O pesquisador deve justificar a escolha de preditores com base em conhecimento substantivo e verificar a robustez dos resultados a especificações alternativas (Abadie, 2021).</p>
<p><strong>Não-unicidade e viés de interpolação.</strong> Um segundo problema, distinto do sobreajuste, é a <strong>não-unicidade dos pesos</strong>. Quando a unidade tratada está no interior do envoltório convexo (<em>convex hull</em>) de muitos doadores, pode haver múltiplas combinações de pesos que reproduzem igualmente bem os dados pré-tratamento — mas que divergem nas previsões pós-tratamento. Isso ocorre quando a informação pré-tratamento não identifica uma combinação única de doadores; com muitos doadores em relação aos preditores disponíveis, múltiplas soluções podem produzir o mesmo ajuste.</p>
<p>Para entender por que isso é problemático, considere um exemplo simples. Suponha que a unidade tratada tem trajetória pré-tratamento idêntica a dois doadores, A e B. Os pesos <span class="math inline">\((1, 0)\)</span> e <span class="math inline">\((0, 1)\)</span> produzem o mesmo ajuste pré-tratamento, mas se A e B divergirem no pós-tratamento, as estimativas do efeito causal serão diferentes conforme a solução escolhida pelo otimizador. Pior, o otimizador pode selecionar uma combinação que usa doadores “distantes” da unidade tratada — produzindo o que Abadie e L’Hour (2021) chamam de <strong>viés de interpolação</strong>.</p>
<p>Uma extensão posterior, motivada sobretudo por aplicações com dados desagregados e muitas unidades tratadas, é o SCM penalizado de Abadie e L’Hour (2021). A ideia é adicionar uma penalidade que favorece pesos associados a doadores <strong>mais similares</strong> à unidade tratada. Para fixar a intuição, no caso de uma unidade tratada, o problema penalizado pode ser escrito como:</p>
<p><span class="math display">\[
\min_{\omega_1, \ldots, \omega_{N_0}} \sum_t \left\{ \left(Y_{N,t} - \sum_{i=1}^{N_0} \omega_i Y_{i,t}\right)^2 + \lambda \sum_{i=1}^{N_0} \omega_i (Y_{N,t} - Y_{i,t})^2 \right\}
\]</span></p>
<p>sujeito a <span class="math inline">\(\omega_i \geq 0\)</span> e <span class="math inline">\(\sum_i \omega_i = 1\)</span>, com <span class="math inline">\(\lambda &gt; 0\)</span>. O segundo termo penaliza o uso de doadores cujas trajetórias individuais são distantes da unidade tratada. Isso ajuda a selecionar uma solução única e reduz o viés de interpolação. No caso canônico com uma única unidade tratada e um <em>donor pool</em> pequeno, porém, esse problema tende a ser menos central e costuma ser tratado por escolhas substantivas de preditores e de unidades doadoras. Robbins et al. (2017) propõem uma abordagem alternativa para dados micro ou desagregados: escolher, dentre as soluções ótimas, os pesos mais próximos de pesos iguais — evitando dependência excessiva de poucos doadores.</p>
</div>
<div id="como-a-literatura-se-move-a-partir-do-scm" class="section level3 hasAnchor" number="12.2.4">
<h3><span class="header-section-number">12.2.4</span> Como a literatura se move a partir do SCM<a href="controle-sintético-e-estimação-contrafactual.html#como-a-literatura-se-move-a-partir-do-scm" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A comparação com regressão organiza a sequência de métodos deste capítulo:</p>
<ol style="list-style-type: decimal">
<li><strong>Regressão:</strong> pesos implícitos, possivelmente negativos e não esparsos, com extrapolação livre pela forma funcional.</li>
<li><strong>SCM clássico:</strong> pesos convexos, explícitos e auditáveis, com menor extrapolação, mas possível rigidez quando a unidade tratada está fora do <em>convex hull</em>.</li>
<li><strong>SCM aumentado:</strong> começa com o SCM e adiciona uma correção por modelo de outcome. Permite alguma extrapolação, mas a ancora no contrafactual sintético.</li>
<li><strong>Doudchenko e Imbens:</strong> mostram a conexão entre SCM, regressão e DiD ao permitir intercepto e relaxar restrições de peso.</li>
<li><strong>SDiD:</strong> mantém a lógica de pesos, mas adiciona pesos temporais e efeitos fixos. O estimador final é uma dupla diferença ponderada, não apenas um SCM com outro nome.</li>
<li><strong>IFEct e controle sintético generalizado:</strong> abandonam a convexidade e estimam diretamente fatores latentes. São mais flexíveis, mas dependem mais fortemente do modelo.</li>
</ol>
<p>Essa leitura conecta o SCM a uma ideia mais ampla. Muitos métodos causais usam controles para imputar o contrafactual dos tratados. Em um experimento, a randomização torna os controles bons contrafactuais em média. No <em>matching</em>, comparamos tratados a controles próximos em covariáveis. No DiD, usamos a trajetória dos controles para imputar a trajetória contrafactual sob tendências paralelas. No SCM, construímos uma combinação convexa de controles para reproduzir o pré-tratamento da unidade tratada.</p>
</div>
</div>
<div id="implementação-do-scm-no-r" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> Implementação do SCM no R<a href="#implementa%C3%A7%C3%A3o-do-scm-no-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Usamos o pacote <code>tidysynth</code>, que oferece uma interface moderna para o SCM.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb121-1" tabindex="-1"></a><span class="fu">library</span>(tidysynth)</span>
<span id="cb121-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb121-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb121-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb121-3" tabindex="-1"></a><span class="fu">data</span>(smoking)</span>
<span id="cb121-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb121-4" tabindex="-1"></a></span>
<span id="cb121-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb121-5" tabindex="-1"></a>smoking <span class="sc">%&gt;%</span></span>
<span id="cb121-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb121-6" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span></span>
<span id="cb121-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb121-7" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;Primeiras observações dos dados de vendas de cigarros no pacote tidysynth.&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:cigarro-tidysynth">Tabela 12.3: </span>Primeiras observações dos dados de vendas de cigarros no pacote tidysynth.</caption>
<thead>
<tr class="header">
<th align="left">state</th>
<th align="right">year</th>
<th align="right">cigsale</th>
<th align="right">lnincome</th>
<th align="right">beer</th>
<th align="right">age15to24</th>
<th align="right">retprice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Rhode Island</td>
<td align="right">1970</td>
<td align="right">123.9</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">0.1831579</td>
<td align="right">39.3</td>
</tr>
<tr class="even">
<td align="left">Tennessee</td>
<td align="right">1970</td>
<td align="right">99.8</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">0.1780438</td>
<td align="right">39.9</td>
</tr>
<tr class="odd">
<td align="left">Indiana</td>
<td align="right">1970</td>
<td align="right">134.6</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">0.1765159</td>
<td align="right">30.6</td>
</tr>
<tr class="even">
<td align="left">Nevada</td>
<td align="right">1970</td>
<td align="right">189.5</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">0.1615542</td>
<td align="right">38.9</td>
</tr>
<tr class="odd">
<td align="left">Louisiana</td>
<td align="right">1970</td>
<td align="right">115.9</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">0.1851852</td>
<td align="right">34.3</td>
</tr>
<tr class="even">
<td align="left">Oklahoma</td>
<td align="right">1970</td>
<td align="right">108.4</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">0.1754592</td>
<td align="right">38.4</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-1" tabindex="-1"></a>smoking_out <span class="ot">&lt;-</span></span>
<span id="cb122-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-2" tabindex="-1"></a>  smoking <span class="sc">%&gt;%</span></span>
<span id="cb122-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-3" tabindex="-1"></a>  <span class="fu">synthetic_control</span>(<span class="at">outcome =</span> cigsale,</span>
<span id="cb122-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-4" tabindex="-1"></a>                    <span class="at">unit =</span> state,</span>
<span id="cb122-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-5" tabindex="-1"></a>                    <span class="at">time =</span> year,</span>
<span id="cb122-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-6" tabindex="-1"></a>                    <span class="at">i_unit =</span> <span class="st">&quot;California&quot;</span>,</span>
<span id="cb122-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-7" tabindex="-1"></a>                    <span class="at">i_time =</span> <span class="dv">1988</span>,</span>
<span id="cb122-8"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-8" tabindex="-1"></a>                    <span class="at">generate_placebos=</span>T</span>
<span id="cb122-9"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-9" tabindex="-1"></a>                    ) <span class="sc">%&gt;%</span></span>
<span id="cb122-10"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-10" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1980</span><span class="sc">:</span><span class="dv">1988</span>,</span>
<span id="cb122-11"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-11" tabindex="-1"></a>                     <span class="at">ln_income =</span> <span class="fu">mean</span>(lnincome, <span class="at">na.rm =</span> T),</span>
<span id="cb122-12"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-12" tabindex="-1"></a>                     <span class="at">ret_price =</span> <span class="fu">mean</span>(retprice, <span class="at">na.rm =</span> T),</span>
<span id="cb122-13"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-13" tabindex="-1"></a>                     <span class="at">youth =</span> <span class="fu">mean</span>(age15to24, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span></span>
<span id="cb122-14"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-14" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1984</span><span class="sc">:</span><span class="dv">1988</span>,</span>
<span id="cb122-15"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-15" tabindex="-1"></a>                     <span class="at">beer_sales =</span> <span class="fu">mean</span>(beer, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span></span>
<span id="cb122-16"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-16" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1975</span>,</span>
<span id="cb122-17"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-17" tabindex="-1"></a>                     <span class="at">cigsale_1975 =</span> cigsale) <span class="sc">%&gt;%</span></span>
<span id="cb122-18"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-18" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1980</span>,</span>
<span id="cb122-19"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-19" tabindex="-1"></a>                     <span class="at">cigsale_1980 =</span> cigsale) <span class="sc">%&gt;%</span></span>
<span id="cb122-20"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-20" tabindex="-1"></a>  <span class="fu">generate_predictor</span>(<span class="at">time_window =</span> <span class="dv">1988</span>,</span>
<span id="cb122-21"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-21" tabindex="-1"></a>                     <span class="at">cigsale_1988 =</span> cigsale) <span class="sc">%&gt;%</span></span>
<span id="cb122-22"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-22" tabindex="-1"></a>  <span class="fu">generate_weights</span>(<span class="at">optimization_window =</span> <span class="dv">1970</span><span class="sc">:</span><span class="dv">1988</span>,</span>
<span id="cb122-23"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-23" tabindex="-1"></a>                   <span class="at">margin_ipop =</span> .<span class="dv">02</span>,<span class="at">sigf_ipop =</span> <span class="dv">7</span>,<span class="at">bound_ipop =</span> <span class="dv">6</span></span>
<span id="cb122-24"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-24" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb122-25"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-25" tabindex="-1"></a>  <span class="fu">generate_control</span>()</span>
<span id="cb122-26"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-26" tabindex="-1"></a></span>
<span id="cb122-27"><a href="controle-sintético-e-estimação-contrafactual.html#cb122-27" tabindex="-1"></a>smoking_out <span class="sc">%&gt;%</span> <span class="fu">plot_trends</span>(<span class="at">time_window =</span> <span class="dv">1970</span><span class="sc">:</span><span class="dv">2000</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cigarro-tidysynth"></span>
<img src="bookdownproj_files/figure-html/cigarro-tidysynth-1.png" alt="Trajetória observada da Califórnia e controle sintético estimado pelo pacote tidysynth." width="672" />
<p class="caption">
Figura 12.3: Trajetória observada da Califórnia e controle sintético estimado pelo pacote tidysynth.
</p>
</div>
<p>O gráfico mostra que a Califórnia Sintética acompanha bem a trajetória real no período pré-1988, e diverge no período pós — essa divergência é a estimativa do efeito causal.</p>
<p>A quantidade causal de interesse — a diferença entre observado e sintético — pode ser visualizada diretamente:</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb123-1" tabindex="-1"></a>smoking_out <span class="sc">%&gt;%</span> <span class="fu">plot_differences</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cigarro-tidysynth-diferencas"></span>
<img src="bookdownproj_files/figure-html/cigarro-tidysynth-diferencas-1.png" alt="Diferença entre Califórnia observada e controle sintético ao longo do tempo." width="672" />
<p class="caption">
Figura 12.4: Diferença entre Califórnia observada e controle sintético ao longo do tempo.
</p>
</div>
<p>Os pesos atribuídos a cada estado e a cada variável preditora:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb124-1" tabindex="-1"></a>smoking_out <span class="sc">%&gt;%</span> <span class="fu">plot_weights</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cigarro-tidysynth-pesos"></span>
<img src="bookdownproj_files/figure-html/cigarro-tidysynth-pesos-1.png" alt="Pesos atribuídos aos estados doadores e aos preditores no SCM estimado pelo pacote tidysynth." width="672" />
<p class="caption">
Figura 12.5: Pesos atribuídos aos estados doadores e aos preditores no SCM estimado pelo pacote tidysynth.
</p>
</div>
<p>O balanceamento entre a Califórnia real e a sintética nos preditores:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb125-1" tabindex="-1"></a>smoking_out <span class="sc">%&gt;%</span></span>
<span id="cb125-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb125-2" tabindex="-1"></a>  <span class="fu">grab_balance_table</span>() <span class="sc">%&gt;%</span></span>
<span id="cb125-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb125-3" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;Balanceamento entre Califórnia observada e controle sintético nos preditores.&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:cigarro-tidysynth-balanceamento">Tabela 12.4: </span>Balanceamento entre Califórnia observada e controle sintético nos preditores.</caption>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">California</th>
<th align="right">synthetic_California</th>
<th align="right">donor_sample</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ln_income</td>
<td align="right">10.0765586</td>
<td align="right">9.8534864</td>
<td align="right">9.8291968</td>
</tr>
<tr class="even">
<td align="left">ret_price</td>
<td align="right">89.4222234</td>
<td align="right">89.3908482</td>
<td align="right">87.2660819</td>
</tr>
<tr class="odd">
<td align="left">youth</td>
<td align="right">0.1735324</td>
<td align="right">0.1736054</td>
<td align="right">0.1725101</td>
</tr>
<tr class="even">
<td align="left">beer_sales</td>
<td align="right">24.2800003</td>
<td align="right">24.2224860</td>
<td align="right">23.6552632</td>
</tr>
<tr class="odd">
<td align="left">cigsale_1975</td>
<td align="right">127.0999985</td>
<td align="right">126.9914177</td>
<td align="right">136.9315790</td>
</tr>
<tr class="even">
<td align="left">cigsale_1980</td>
<td align="right">120.1999969</td>
<td align="right">120.2204841</td>
<td align="right">138.0894737</td>
</tr>
<tr class="odd">
<td align="left">cigsale_1988</td>
<td align="right">90.0999985</td>
<td align="right">91.3888620</td>
<td align="right">113.8236837</td>
</tr>
</tbody>
</table>
<div id="inferência-por-placebo" class="section level3 hasAnchor" number="12.3.1">
<h3><span class="header-section-number">12.3.1</span> Inferência por placebo<a href="#infer%C3%AAncia-por-placebo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A inferência no SCM é feita por testes placebo. A intuição é a de um teste de permutação: para cada estado do donor pool, fingimos que ele foi tratado e estimamos um SCM. Se o efeito da Califórnia for grande relativo aos placebos, concluímos que é estatisticamente significativo.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb126-1" tabindex="-1"></a>smoking_out <span class="sc">%&gt;%</span> <span class="fu">plot_placebos</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cigarro-tidysynth-placebos"></span>
<img src="bookdownproj_files/figure-html/cigarro-tidysynth-placebos-1.png" alt="Teste placebo do SCM para a Califórnia e os estados doadores." width="672" />
<p class="caption">
Figura 12.6: Teste placebo do SCM para a Califórnia e os estados doadores.
</p>
</div>
<p>O efeito estimado para a Califórnia (linha escura) é claramente maior do que os efeitos placebo (linhas cinzas), sugerindo que a Proposição 99 de fato reduziu o consumo de cigarros.</p>
<p>Para formalizar a inferência, Abadie, Diamond e Hainmueller (2010, seção 4) propõem construir p-valores a partir da distribuição de razões de RMSPE: para cada unidade placebo <span class="math inline">\(i\)</span>, calcula-se a razão entre o RMSPE pós-tratamento e o RMSPE pré-tratamento. Se a razão da unidade tratada for extrema em relação à distribuição dos placebos, o efeito é considerado significativo. Formalmente, seja <span class="math inline">\(\mathcal{P}\)</span> o conjunto de unidades usadas no teste placebo, incluindo a unidade tratada e as unidades doadoras elegíveis. O p-valor é a fração de unidades em <span class="math inline">\(\mathcal{P}\)</span> cuja razão RMSPE é pelo menos tão grande quanto a da unidade tratada:</p>
<p><span class="math display">\[
\text{p-valor} = \frac{1}{N} \sum_{i \in \mathcal{P}} \mathbf{1}[R_i \geq R_{\text{tratada}}]
\]</span></p>
<p>onde <span class="math inline">\(N = |\mathcal{P}|\)</span> e</p>
<p><span class="math display">\[
R_i =
\frac{
\sqrt{\frac{1}{T - T_0}\sum_{t &gt; T_0} (Y_{it} - \hat{Y}_{it}(0))^2}
}{
\sqrt{\frac{1}{T_0}\sum_{t \leq T_0} (Y_{it} - \hat{Y}_{it}(0))^2}
}
\]</span></p>
<p>é a razão entre o RMSPE pós-tratamento e o RMSPE pré-tratamento da unidade <span class="math inline">\(i\)</span>.</p>
<p><strong>Limitação fundamental: o que significam “5%”?</strong> É crucial entender o que esse p-valor realmente mede. Sob a hipótese nula de efeito zero, o teste assume que a unidade tratada “não é diferente” das demais. O p-valor de 5% significa que, <em>se cada uma das <span class="math inline">\(N\)</span> unidades fosse tratada</em>, 5% delas teriam o null rejeitado. Mas isso <strong>não é um nível de significância no sentido frequentista convencional</strong>, porque a unidade tratada geralmente não foi escolhida aleatoriamente entre as <span class="math inline">\(N\)</span> unidades. A Califórnia aprovou a Proposição 99 por razões políticas e sociais específicas — não foi sorteada. Se a Califórnia é sistematicamente diferente dos outros estados (o que é provável, dado que <em>ela</em> adotou a política), o teste de permutação pode ter propriedades de tamanho distorcidas.</p>
<p>Em outras palavras, o teste tem validade exata sob aleatorização do tratamento, mas essa premissa raramente se sustenta em aplicações de controle sintético. Abadie, Diamond e Hainmueller (2015), ao estudar o impacto da reunificação sobre a Alemanha Ocidental, enfrentam esse problema de forma aguda: o que significaria “atribuir a reunificação a outro país”?</p>
<p><strong>Complicações adicionais na prática.</strong> Mesmo aceitando a lógica do teste, duas complicações surgem. Primeira: para algumas unidades placebo, o controle sintético pode ter ajuste pré-tratamento ruim. Isso contamina especialmente estatísticas baseadas apenas no erro pós-tratamento em nível; por isso, a razão RMSPE pós/pré é preferível, e também é comum descartar placebos com RMSPE pré-tratamento acima de um limiar. Segunda: com poucas unidades elegíveis no exercício placebo (<span class="math inline">\(N\)</span> pequeno), o menor p-valor possível é <span class="math inline">\(1/N\)</span>. No exemplo da Califórnia, <span class="math inline">\(N = 39\)</span> porque a amostra contém a Califórnia e 38 estados doadores, não todos os estados dos EUA; portanto, o menor p-valor é <span class="math inline">\(1/39 \approx 0.026\)</span>, o que limita a precisão inferencial.</p>
<p><strong>Inferência conformal como alternativa.</strong> Chernozhukov, Wüthrich e Zhu (2021) propõem uma solução elegante: em vez de permutar <em>unidades</em>, permutar <em>períodos de tempo</em>. A ideia é que, sob a hipótese nula de efeito zero, os resíduos <span class="math inline">\(Y_{N,t} - \hat{Y}_{N,t}(0)\)</span> nos períodos pós-tratamento deveriam ser indistinguíveis dos resíduos pré-tratamento. O teste conformal constrói p-valores permutando esses resíduos ao longo do tempo — sem necessidade de assumir que o tratamento foi atribuído aleatoriamente entre unidades. Isso fornece inferência com validade em amostra finita, mesmo com uma única unidade tratada, desde que os erros sejam permutáveis ao longo do tempo.</p>
</div>
<div id="diagnósticos-de-robustez-do-scm" class="section level3 hasAnchor" number="12.3.2">
<h3><span class="header-section-number">12.3.2</span> Diagnósticos de robustez do SCM<a href="#diagn%C3%B3sticos-de-robustez-do-scm" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Além dos testes placebo, dois diagnósticos adicionais são recomendados para avaliar a robustez do SCM (Abadie, 2021):</p>
<p><strong>Teste de backdating.</strong> O pesquisador finge que o tratamento ocorreu em um período anterior ao verdadeiro — por exemplo, 5 ou 10 anos antes — e reestima o SCM. Se o controle sintético divergir da unidade tratada <em>antes</em> do verdadeiro tratamento, isso sugere que o modelo não está capturando adequadamente a dinâmica pré-tratamento e que as estimativas pós-tratamento podem ser enviesadas. Abadie (2021) ilustra essa abordagem no caso da reunificação alemã, mostrando que a Alemanha Ocidental Sintética acompanha de perto o PIB real até 1990.</p>
<p><strong>Teste leave-one-out.</strong> Remove-se cada doador contribuinte (com peso não-zero) do donor pool, um de cada vez, e reestima-se o SCM. Se as estimativas são robustas — isto é, se o efeito estimado não muda substancialmente ao remover qualquer doador individual — há maior confiança de que o resultado não depende de uma única unidade de controle. Se, ao contrário, a remoção de um doador altera dramaticamente as estimativas, isso indica fragilidade.</p>
<p><strong>Sensibilidade ao donor pool.</strong> Mais geralmente, os resultados do SCM podem ser sensíveis à composição do donor pool. O pesquisador deve justificar os critérios de inclusão e exclusão de unidades de controle com base em conhecimento substantivo — por exemplo, excluindo estados com políticas antitabaco similares ou com características estruturais muito diferentes (Abadie, 2021). Recomenda-se verificar a robustez das estimativas a variações na composição do donor pool.</p>
</div>
</div>
<div id="do-scm-aos-modelos-de-fatores" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Do SCM aos modelos de fatores<a href="controle-sintético-e-estimação-contrafactual.html#do-scm-aos-modelos-de-fatores" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Como vimos na seção anterior, o SCM é justificado por um modelo linear de fatores: <span class="math inline">\(Y_{it}(0) = \delta_t + \theta_t Z_i + \lambda_t \mu_i + \varepsilon_{it}\)</span>. Se os pesos reproduzem os preditores pré-tratamento, eles também reproduzem os fatores latentes, e o viés desaparece. Mas isso levanta uma questão natural: <strong>se o processo gerador de dados é um modelo de fatores, por que não estimar os fatores diretamente?</strong></p>
<p>No SCM clássico, a resposta é pragmática. Em estudos de caso com uma única ou poucas unidades tratadas, geralmente não há graus de liberdade suficientes para estimar fatores latentes de forma confiável. O SCM contorna essa limitação por meio de pesos convexos: ele não estima diretamente os fatores, mas escolhe uma combinação de controles que reproduz a trajetória pré-tratamento da unidade tratada e, sob certas condições, também aproxima seus componentes latentes relevantes.</p>
<p>O Synthetic DiD segue uma lógica próxima, mas combina essa intuição de balanceamento com diferenças-em-diferenças. Em vez de estimar diretamente os fatores latentes, o método escolhe pesos para unidades e períodos de modo a tornar a comparação tratada-controle mais local e plausível, e então estima o efeito por uma regressão de diferenças-em-diferenças ponderada. Assim como o SCM, o SDiD pode ser interpretado sob um modelo de fatores latentes, mas sua implementação continua sendo baseada em pesos, não na estimação explícita dos fatores.</p>
<p>Já os estimadores contrafactuais de Liu, Wang e Xu (2024), como FEct, IFEct e matrix completion, tomam a estrutura latente do painel como objeto mais direto de estimação. Neles, os resultados não-tratados observados são usados para estimar uma superfície contrafactual de baixa dimensão, que depois é imputada para as observações tratadas. A diferença central, portanto, é o modo como cada método explora a estrutura latente do painel: por balanceamento implícito no SCM e no SDiD, ou por estimação explícita em IFEct e matrix completion.</p>
</div>
<div id="framework-de-estimação-contrafactual" class="section level2 hasAnchor" number="12.5">
<h2><span class="header-section-number">12.5</span> Framework de estimação contrafactual<a href="#framework-de-estima%C3%A7%C3%A3o-contrafactual" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O SCM clássico é uma ferramenta poderosa para estudos de caso com uma única unidade tratada. Mas e quando temos múltiplas unidades tratadas com tratamento escalonado no tempo? E quando queremos diagnósticos formais sobre a qualidade da estimação?</p>
<p>Liu, Wang e Xu (2024) propõem um framework unificado de <strong>estimação contrafactual</strong> que generaliza o SCM e o DiD por imputação (para um survey mais amplo de modelos causais para dados de painel, ver Arkhangelsky e Imbens, 2024). A ideia central é a mesma: estimar <span class="math inline">\(Y_{it}(0)\)</span> para as observações tratadas e calcular o efeito como a diferença entre observado e contrafactual.</p>
<div id="setup" class="section level3 hasAnchor" number="12.5.1">
<h3><span class="header-section-number">12.5.1</span> Setup<a href="controle-sintético-e-estimação-contrafactual.html#setup" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Considere um painel com <span class="math inline">\(N\)</span> unidades e <span class="math inline">\(T\)</span> períodos. O indicador de tratamento <span class="math inline">\(D_{it}\)</span> pode variar por unidade e tempo (tratamento escalonado, e inclusive pode “ligar e desligar”). Particione as observações em dois conjuntos:</p>
<ul>
<li><span class="math inline">\(\mathcal{C}_0\)</span>: observações não-tratadas (<span class="math inline">\(D_{it} = 0\)</span>), usadas para estimar o modelo</li>
<li><span class="math inline">\(\mathcal{M}\)</span>: observações tratadas (<span class="math inline">\(D_{it} = 1\)</span>), para as quais imputamos o contrafactual</li>
</ul>
<p>O efeito individual do tratamento é <span class="math inline">\(\delta_{it} = Y_{it}(1) - Y_{it}(0)\)</span>, e o estimando é:
<span class="math display">\[
ATT = \mathbb{E}[\delta_{it} \mid D_{it} = 1] = \frac{1}{|\mathcal{M}|} \sum_{(i,t) \in \mathcal{M}} \delta_{it}
\]</span></p>
<p>A segunda igualdade vale sob uma interpretação <em>design-based</em>, em que o painel observado é a população de interesse (não uma amostra de uma superpopulação). Nesse caso, a esperança é sobre a atribuição de tratamento, e a média amostral coincide com o parâmetro populacional.</p>
</div>
<div id="estratégia-de-estimação-em-quatro-passos" class="section level3 hasAnchor" number="12.5.2">
<h3><span class="header-section-number">12.5.2</span> Estratégia de estimação em quatro passos<a href="#estrat%C3%A9gia-de-estima%C3%A7%C3%A3o-em-quatro-passos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><strong>Ajustar</strong> o modelo de <span class="math inline">\(Y_{it}(0)\)</span> usando apenas as observações em <span class="math inline">\(\mathcal{C}_0\)</span></li>
<li><strong>Prever</strong> o contrafactual <span class="math inline">\(\hat{Y}_{it}(0)\)</span> para cada <span class="math inline">\((i,t) \in \mathcal{M}\)</span></li>
<li><strong>Calcular</strong> <span class="math inline">\(\hat{\delta}_{it} = Y_{it} - \hat{Y}_{it}(0)\)</span> para cada observação tratada</li>
<li><strong>Agregar</strong> os efeitos: <span class="math inline">\(\widehat{ATT} = \frac{1}{|\mathcal{M}|} \sum_{(i,t) \in \mathcal{M}} \hat{\delta}_{it}\)</span></li>
</ol>
<p>Essa estratégia evita o problema de pesos negativos do TWFE (capítulo 8): cada observação tratada recebe peso uniforme <span class="math inline">\(1/|\mathcal{M}|\)</span> na agregação.</p>
</div>
<div id="suposições-de-identificação-1" class="section level3 hasAnchor" number="12.5.3">
<h3><span class="header-section-number">12.5.3</span> Suposições de identificação<a href="#suposi%C3%A7%C3%B5es-de-identifica%C3%A7%C3%A3o-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O framework requer três suposições (Liu et al., 2024, p. 163):</p>
<ul>
<li><strong>Suposição 1 (Forma funcional)</strong>: <span class="math inline">\(Y_{it}(0) = h(U_{it}) + \varepsilon_{it}\)</span>, onde <span class="math inline">\(h\)</span> é uma função desconhecida e <span class="math inline">\(U_{it}\)</span> são fatores latentes.</li>
<li><strong>Suposição 2 (Exogeneidade estrita)</strong>: <span class="math inline">\(\mathbb{E}[\varepsilon_{it} | U_{i1}, \ldots, U_{iT}, D_{i1}, \ldots, D_{iT}] = 0\)</span> — os erros são não-correlacionados com os fatores e o tratamento.</li>
<li><strong>Suposição 3 (Decomposição de baixo posto)</strong>: <span class="math inline">\(h(U_{it})\)</span> pode ser decomposta em componentes de baixa dimensionalidade.</li>
</ul>
<p>A Suposição 3 é o que diferencia os três estimadores: no caso mais simples, <span class="math inline">\(h(U_{it}) = \alpha_i + \xi_t\)</span> (efeitos fixos aditivos, como no DiD). No caso mais flexível, <span class="math inline">\(h(U_{it}) = \alpha_i + \xi_t + \lambda&#39;_i f_t\)</span> (fatores interativos). Eles são “interativos” porque <span class="math inline">\(\lambda_i\)</span> representa cargas específicas da unidade <span class="math inline">\(i\)</span> e <span class="math inline">\(f_t\)</span> representa fatores comuns no período <span class="math inline">\(t\)</span>; o termo <span class="math inline">\(\lambda&#39;_i f_t\)</span> permite que o mesmo fator temporal afete cada unidade com intensidade diferente. Diferentemente dos efeitos fixos aditivos, portanto, a heterogeneidade entre unidades pode variar ao longo do tempo.</p>
</div>
<div id="conexão-com-did" class="section level3 hasAnchor" number="12.5.4">
<h3><span class="header-section-number">12.5.4</span> Conexão com DiD<a href="#conex%C3%A3o-com-did" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O DiD é um caso especial deste framework. Quando <span class="math inline">\(h(U_{it}) = \alpha_i + \xi_t\)</span> e usamos os dados de controle para estimar esses efeitos fixos e depois imputamos, obtemos o estimador de DiD por imputação de Borusyak, Jaravel e Spiess (2024), que vimos no capítulo 8. O framework de Liu et al. vai além ao permitir modelos mais flexíveis.</p>
</div>
</div>
<div id="três-estimadores-contrafactuais" class="section level2 hasAnchor" number="12.6">
<h2><span class="header-section-number">12.6</span> Três estimadores contrafactuais<a href="#tr%C3%AAs-estimadores-contrafactuais" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O framework de Liu et al. (2024) oferece três estimadores, implementados no pacote <code>fect</code> (Fixed Effects Counterfactual Estimators).</p>
<div id="fect-efeitos-fixos" class="section level3 hasAnchor" number="12.6.1">
<h3><span class="header-section-number">12.6.1</span> FEct: efeitos fixos<a href="controle-sintético-e-estimação-contrafactual.html#fect-efeitos-fixos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O modelo mais simples assume:
<span class="math display">\[
Y_{it}(0) = X&#39;_{it}\beta + \alpha_i + \xi_t + \varepsilon_{it}
\]</span></p>
<p>Esse é o modelo TWFE — os mesmos efeitos fixos aditivos do DiD. A diferença em relação ao DiD tradicional é a <em>estratégia de estimação</em>: em vez de regredir <span class="math inline">\(Y\)</span> em <span class="math inline">\(D\)</span> com efeitos fixos (o que pode gerar pesos negativos com tratamento heterogêneo), o FEct estima <span class="math inline">\(\alpha_i\)</span>, <span class="math inline">\(\xi_t\)</span> e <span class="math inline">\(\beta\)</span> usando apenas as observações não-tratadas, e depois imputa o contrafactual para as tratadas.</p>
<p>Isso é equivalente ao estimador de imputação de Borusyak et al. (2024), que discutimos no capítulo 8.</p>
<p><strong>Nota sobre covariáveis.</strong> O termo <span class="math inline">\(X&#39;_{it}\beta\)</span> permite incluir covariáveis no modelo. As mesmas precauções discutidas no capítulo 8 (seção sobre DiD com covariáveis) se aplicam: covariáveis variantes no tempo que podem ser afetadas pelo tratamento são <em>bad controls</em> e não devem ser incluídas diretamente. A vantagem da abordagem de imputação (FEct/IFEct) é que <span class="math inline">\(\beta\)</span> é estimado usando apenas observações não-tratadas, evitando a contaminação que ocorre no TWFE ingênuo.</p>
</div>
<div id="ifect-fatores-interativos" class="section level3 hasAnchor" number="12.6.2">
<h3><span class="header-section-number">12.6.2</span> IFEct: fatores interativos<a href="controle-sintético-e-estimação-contrafactual.html#ifect-fatores-interativos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O modelo de fatores interativos adiciona um componente multiplicativo:
<span class="math display">\[
Y_{it}(0) = X&#39;_{it}\beta + \alpha_i + \xi_t + \lambda&#39;_i f_t + \varepsilon_{it}
\]</span></p>
<p>O termo <span class="math inline">\(\lambda&#39;_i f_t\)</span> captura confundidores variantes no tempo de forma heterogênea: <span class="math inline">\(f_t\)</span> é um vetor de <span class="math inline">\(r\)</span> fatores comuns (que variam no tempo), e <span class="math inline">\(\lambda_i\)</span> é o vetor de cargas fatoriais (que variam por unidade). Quando <span class="math inline">\(f_t\)</span> é constante, o componente <span class="math inline">\(\lambda&#39;_i f_t\)</span> é absorvido pelo efeito fixo de unidade <span class="math inline">\(\alpha_i\)</span>, e o modelo reduz ao caso aditivo (FEct); quando <span class="math inline">\(\lambda_i\)</span> é constante, o componente é absorvido pelo efeito fixo de tempo <span class="math inline">\(\xi_t\)</span>.</p>
<p>A vantagem em relação ao FEct é que o IFEct <strong>relaxa a suposição de tendências paralelas</strong>: não exige que todas as unidades sigam a mesma tendência temporal. Basta que as trajetórias sejam explicáveis por um número pequeno de fatores latentes — uma suposição mais fraca e frequentemente mais realista.</p>
<p>O número de fatores <span class="math inline">\(r\)</span> é escolhido por validação cruzada. Na prática, o pacote <code>fect</code> testa <span class="math inline">\(r = 0, 1, 2, \ldots, r_{max}\)</span> e escolhe o valor que minimiza o erro de predição nos dados não-tratados.</p>
</div>
<div id="mc-matrix-completion" class="section level3 hasAnchor" number="12.6.3">
<h3><span class="header-section-number">12.6.3</span> MC: Matrix Completion<a href="controle-sintético-e-estimação-contrafactual.html#mc-matrix-completion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O estimador MC (Athey, Bayati, Doudchenko, Imbens e Khosravi, 2021) trata o problema como <em>completação de matriz</em>. A ideia é que a matriz <span class="math inline">\(\mathbf{Y}(0)\)</span> de resultados potenciais sem tratamento tem estrutura de baixo posto — pode ser bem aproximada por uma matriz de posto <span class="math inline">\(r\)</span> pequeno. O modelo é:
<span class="math display">\[
\mathbf{Y}(0) = \mathbf{X}\beta + \mathbf{L} + \varepsilon
\]</span>
onde <span class="math inline">\(\mathbf{L}\)</span> é uma matriz de baixo posto. Em vez de selecionar <span class="math inline">\(r\)</span> fatores diretamente (como no IFEct), o MC penaliza a norma nuclear <span class="math inline">\(\|\mathbf{L}\|_*\)</span>. Essa penalização funciona como um substituto convexo para favorecer matrizes de baixo posto. Isso faz um “soft impute”: os valores singulares são encolhidos continuamente, em vez de truncados.</p>
<p>A diferença prática entre IFEct e MC é:</p>
<ul>
<li><strong>IFEct</strong> faz “hard impute”: escolhe <span class="math inline">\(r\)</span> fatores e descarta o resto</li>
<li><strong>MC</strong> faz “soft impute”: penaliza a norma nuclear, encolhendo todos os valores singulares</li>
</ul>
<p>Quando a penalização <span class="math inline">\(\lambda_L \to \infty\)</span> (ou <span class="math inline">\(r = 0\)</span>), ambos reduzem ao FEct (efeitos fixos aditivos).</p>
</div>
<div id="demonstração-com-dados-da-califórnia" class="section level3 hasAnchor" number="12.6.4">
<h3><span class="header-section-number">12.6.4</span> Demonstração com dados da Califórnia<a href="#demonstra%C3%A7%C3%A3o-com-dados-da-calif%C3%B3rnia" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Aplicamos os três estimadores aos mesmos dados de cigarros usados no SCM.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-1" tabindex="-1"></a><span class="fu">library</span>(fect)</span>
<span id="cb127-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb127-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-3" tabindex="-1"></a></span>
<span id="cb127-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-4" tabindex="-1"></a><span class="fu">data</span>(smoking, <span class="at">package =</span> <span class="st">&quot;tidysynth&quot;</span>)</span>
<span id="cb127-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-5" tabindex="-1"></a></span>
<span id="cb127-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-6" tabindex="-1"></a><span class="co"># Preparar dados para fect</span></span>
<span id="cb127-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-7" tabindex="-1"></a>df_fect <span class="ot">&lt;-</span> smoking <span class="sc">%&gt;%</span></span>
<span id="cb127-8"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-8" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb127-9"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-9" tabindex="-1"></a>    <span class="at">D =</span> <span class="fu">ifelse</span>(state <span class="sc">==</span> <span class="st">&quot;California&quot;</span> <span class="sc">&amp;</span> year <span class="sc">&gt;=</span> <span class="dv">1989</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb127-10"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-10" tabindex="-1"></a>    <span class="at">unit_id =</span> <span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(state))</span>
<span id="cb127-11"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-11" tabindex="-1"></a>  )</span>
<span id="cb127-12"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-12" tabindex="-1"></a></span>
<span id="cb127-13"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-13" tabindex="-1"></a><span class="co"># FEct: efeitos fixos (equivalente a DiD por imputação)</span></span>
<span id="cb127-14"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-14" tabindex="-1"></a>out_fe <span class="ot">&lt;-</span> <span class="fu">fect</span>(cigsale <span class="sc">~</span> D, <span class="at">data =</span> df_fect,</span>
<span id="cb127-15"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-15" tabindex="-1"></a>               <span class="at">index =</span> <span class="fu">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>),</span>
<span id="cb127-16"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-16" tabindex="-1"></a>               <span class="at">method =</span> <span class="st">&quot;fe&quot;</span>,</span>
<span id="cb127-17"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-17" tabindex="-1"></a>               <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">nboots =</span> <span class="dv">200</span>,</span>
<span id="cb127-18"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-18" tabindex="-1"></a>               <span class="at">parallel =</span> <span class="cn">FALSE</span>)</span>
<span id="cb127-19"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-19" tabindex="-1"></a></span>
<span id="cb127-20"><a href="controle-sintético-e-estimação-contrafactual.html#cb127-20" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;FEct - ATT estimado:&quot;</span>, <span class="fu">round</span>(out_fe<span class="sc">$</span>att.avg, <span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## FEct - ATT estimado: -27.35</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-1" tabindex="-1"></a><span class="co"># IFEct: fatores interativos (r escolhido por CV)</span></span>
<span id="cb129-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-2" tabindex="-1"></a>out_ife <span class="ot">&lt;-</span> <span class="fu">fect</span>(cigsale <span class="sc">~</span> D, <span class="at">data =</span> df_fect,</span>
<span id="cb129-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-3" tabindex="-1"></a>                <span class="at">index =</span> <span class="fu">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>),</span>
<span id="cb129-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-4" tabindex="-1"></a>                <span class="at">method =</span> <span class="st">&quot;ife&quot;</span>,</span>
<span id="cb129-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-5" tabindex="-1"></a>                <span class="at">r =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>),</span>
<span id="cb129-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-6" tabindex="-1"></a>                <span class="at">CV =</span> <span class="cn">TRUE</span>,</span>
<span id="cb129-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-7" tabindex="-1"></a>                <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">nboots =</span> <span class="dv">200</span>,</span>
<span id="cb129-8"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-8" tabindex="-1"></a>                <span class="at">parallel =</span> <span class="cn">FALSE</span>)</span>
<span id="cb129-9"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-9" tabindex="-1"></a></span>
<span id="cb129-10"><a href="controle-sintético-e-estimação-contrafactual.html#cb129-10" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;IFEct - ATT estimado:&quot;</span>, <span class="fu">round</span>(out_ife<span class="sc">$</span>att.avg, <span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## IFEct - ATT estimado: -24.62</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb131-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Número de fatores escolhido:&quot;</span>, out_ife<span class="sc">$</span>r.cv, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Número de fatores escolhido: 3</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb133-1" tabindex="-1"></a><span class="co"># MC: Matrix Completion</span></span>
<span id="cb133-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb133-2" tabindex="-1"></a>out_mc <span class="ot">&lt;-</span> <span class="fu">fect</span>(cigsale <span class="sc">~</span> D, <span class="at">data =</span> df_fect,</span>
<span id="cb133-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb133-3" tabindex="-1"></a>               <span class="at">index =</span> <span class="fu">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>),</span>
<span id="cb133-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb133-4" tabindex="-1"></a>               <span class="at">method =</span> <span class="st">&quot;mc&quot;</span>,</span>
<span id="cb133-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb133-5" tabindex="-1"></a>               <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">nboots =</span> <span class="dv">200</span>,</span>
<span id="cb133-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb133-6" tabindex="-1"></a>               <span class="at">parallel =</span> <span class="cn">FALSE</span>)</span>
<span id="cb133-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb133-7" tabindex="-1"></a></span>
<span id="cb133-8"><a href="controle-sintético-e-estimação-contrafactual.html#cb133-8" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;MC - ATT estimado:&quot;</span>, <span class="fu">round</span>(out_mc<span class="sc">$</span>att.avg, <span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## MC - ATT estimado: -25.91</code></pre>
<p>O gráfico de efeitos dinâmicos (<em>dynamic treatment effects</em>) mostra a evolução do efeito estimado ao longo do tempo, incluindo o período pré-tratamento (que deve ser próximo de zero se o modelo estiver bem especificado):</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb135-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb135-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb135-2" tabindex="-1"></a><span class="fu">plot</span>(out_fe, <span class="at">main =</span> <span class="st">&quot;FEct (Efeitos Fixos)&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Efeito estimado&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Períodos relativos ao tratamento&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:fect-dinamico-1"></span>
<img src="bookdownproj_files/figure-html/fect-dinamico-1.png" alt="Efeitos dinâmicos estimados pelo FEct no exemplo da Califórnia." width="960" />
<p class="caption">
Figura 12.7: Efeitos dinâmicos estimados pelo FEct no exemplo da Califórnia.
</p>
</div>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb136-1" tabindex="-1"></a><span class="fu">plot</span>(out_ife, <span class="at">main =</span> <span class="st">&quot;IFEct (Fatores Interativos)&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Efeito estimado&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Períodos relativos ao tratamento&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:fect-dinamico-2"></span>
<img src="bookdownproj_files/figure-html/fect-dinamico-2.png" alt="Efeitos dinâmicos estimados pelo IFEct no exemplo da Califórnia." width="960" />
<p class="caption">
Figura 12.8: Efeitos dinâmicos estimados pelo IFEct no exemplo da Califórnia.
</p>
</div>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb137-1" tabindex="-1"></a><span class="fu">plot</span>(out_mc, <span class="at">main =</span> <span class="st">&quot;MC (Matrix Completion)&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Efeito estimado&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Períodos relativos ao tratamento&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:fect-dinamico-3"></span>
<img src="bookdownproj_files/figure-html/fect-dinamico-3.png" alt="Efeitos dinâmicos estimados por matrix completion no exemplo da Califórnia." width="960" />
<p class="caption">
Figura 12.9: Efeitos dinâmicos estimados por matrix completion no exemplo da Califórnia.
</p>
</div>
<p>Os três estimadores devem concordar no sinal e magnitude aproximada do efeito (redução nas vendas de cigarros). Divergências no período pré-tratamento indicam diferenças na qualidade do ajuste — que é exatamente o que os diagnósticos formais da próxima seção avaliam.</p>
</div>
</div>
<div id="diagnósticos" class="section level2 hasAnchor" number="12.7">
<h2><span class="header-section-number">12.7</span> Diagnósticos<a href="#diagn%C3%B3sticos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Uma vantagem do framework de Liu et al. (2024) é oferecer diagnósticos formais para avaliar a qualidade da estimação contrafactual. Esses diagnósticos vão além da inspeção visual e fornecem testes estatísticos.</p>
<div id="efeitos-dinâmicos" class="section level3 hasAnchor" number="12.7.1">
<h3><span class="header-section-number">12.7.1</span> Efeitos dinâmicos<a href="#efeitos-din%C3%A2micos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O gráfico de efeitos dinâmicos (<em>gap plot</em>) mostra <span class="math inline">\(\hat{\delta}_{it}\)</span> para cada período relativo ao tratamento. No período pré-tratamento, esses efeitos devem ser próximos de zero — se não forem, o modelo está falhando em reproduzir os dados pré-tratamento e as estimativas pós-tratamento são suspeitas.</p>
<p>Diferentemente do event study tradicional do DiD (capítulo 8), o gráfico do <code>fect</code> não precisa de uma categoria de referência arbitrária: todos os períodos pré-tratamento são informativos.</p>
</div>
<div id="placebo-test" class="section level3 hasAnchor" number="12.7.2">
<h3><span class="header-section-number">12.7.2</span> Placebo test<a href="controle-sintético-e-estimação-contrafactual.html#placebo-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>O teste placebo “esconde” parte dos períodos pré-tratamento e finge que o tratamento começou antes. Formalmente, remove os últimos <span class="math inline">\(L\)</span> períodos pré-tratamento de <span class="math inline">\(\mathcal{C}_0\)</span>, reestima o modelo, e calcula <span class="math inline">\(\hat{\delta}_{it}\)</span> para esses períodos “escondidos”. Se o modelo for bem especificado, esses efeitos placebo devem ser zero.</p>
<p>Liu et al. (2024) propõem dois critérios:</p>
<ol style="list-style-type: decimal">
<li><strong>Teste t</strong>: a média dos efeitos placebo é significativamente diferente de zero?</li>
<li><strong>Teste de equivalência (TOST)</strong>: os efeitos placebo estão dentro de um intervalo de equivalência <span class="math inline">\([-\Delta, \Delta]\)</span>?</li>
</ol>
<p>O teste de equivalência é preferível porque um teste t com baixo poder pode falhar em rejeitar (falso conforto), enquanto o TOST requer evidência <em>positiva</em> de que os efeitos são pequenos.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-1" tabindex="-1"></a><span class="co"># Placebo test com IFEct (r fixo, sem CV)</span></span>
<span id="cb138-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-2" tabindex="-1"></a>out_ife_placebo <span class="ot">&lt;-</span> <span class="fu">fect</span>(cigsale <span class="sc">~</span> D, <span class="at">data =</span> df_fect,</span>
<span id="cb138-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-3" tabindex="-1"></a>                        <span class="at">index =</span> <span class="fu">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>),</span>
<span id="cb138-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-4" tabindex="-1"></a>                        <span class="at">method =</span> <span class="st">&quot;ife&quot;</span>,</span>
<span id="cb138-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-5" tabindex="-1"></a>                        <span class="at">r =</span> <span class="dv">2</span>,</span>
<span id="cb138-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-6" tabindex="-1"></a>                        <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">nboots =</span> <span class="dv">200</span>,</span>
<span id="cb138-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-7" tabindex="-1"></a>                        <span class="at">parallel =</span> <span class="cn">FALSE</span>,</span>
<span id="cb138-8"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-8" tabindex="-1"></a>                        <span class="at">placeboTest =</span> <span class="cn">TRUE</span>,</span>
<span id="cb138-9"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-9" tabindex="-1"></a>                        <span class="at">placebo.period =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">0</span>))</span>
<span id="cb138-10"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-10" tabindex="-1"></a></span>
<span id="cb138-11"><a href="controle-sintético-e-estimação-contrafactual.html#cb138-11" tabindex="-1"></a><span class="fu">plot</span>(out_ife_placebo, <span class="at">type =</span> <span class="st">&quot;equiv&quot;</span>, <span class="at">main =</span> <span class="st">&quot;Teste de Equivalência (IFEct)&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:fect-placebo"></span>
<img src="bookdownproj_files/figure-html/fect-placebo-1.png" alt="Teste de equivalência placebo para o modelo IFEct no exemplo da Califórnia." width="768" />
<p class="caption">
Figura 12.10: Teste de equivalência placebo para o modelo IFEct no exemplo da Califórnia.
</p>
</div>
</div>
<div id="teste-de-no-carryover" class="section level3 hasAnchor" number="12.7.3">
<h3><span class="header-section-number">12.7.3</span> Teste de no-carryover<a href="controle-sintético-e-estimação-contrafactual.html#teste-de-no-carryover" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Em alguns contextos, o tratamento pode ter efeitos residuais: mesmo após o tratamento ser “desligado”, a unidade ainda é afetada. O teste de carryover esconde períodos imediatamente após o tratamento ser removido (se aplicável) e verifica se existem efeitos residuais. Em contextos como o nosso (tratamento absorvente), esse teste não se aplica diretamente, mas é relevante para designs em que o tratamento liga e desliga.</p>
</div>
</div>
<div id="synthetic-did" class="section level2 hasAnchor" number="12.8">
<h2><span class="header-section-number">12.8</span> Synthetic DiD<a href="controle-sintético-e-estimação-contrafactual.html#synthetic-did" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>O Controle Sintético clássico e o framework de estimação contrafactual resolvem o problema de imputação de formas diferentes. Uma terceira abordagem, proposta por Arkhangelsky, Athey, Hirshberg, Imbens e Wager (2021), combina as ideias do SCM e do DiD em um único estimador: o <strong>Synthetic DiD</strong> (SDiD).</p>
<p>Para entender o SDiD, é útil ver os três estimadores — SC, DiD e SDiD — lado a lado, seguindo a formulação unificada de Arkhangelsky et al. (2021) e a exposição de Arkhangelsky e Imbens (2024).</p>
<p>O <strong>Controle Sintético</strong> pode ser reescrito como um problema de mínimos quadrados ponderados:
<span class="math display">\[
(\hat{\mu}, \hat{\gamma}, \hat{\tau}^{SC}) = \arg\min_{\mu, \gamma, \tau}\ \sum_i \sum_t (y_{it} - \mu - \gamma_t - D_{it}\tau)^2 \hat{w}_i
\]</span>
Note que não há efeitos fixos de unidade (<span class="math inline">\(\alpha_i\)</span>) — os pesos <span class="math inline">\(\hat{w}_i\)</span> “fazem o trabalho” de tornar os controles comparáveis.</p>
<p>O <strong>DiD</strong> (via TWFE) inclui efeitos fixos mas dá peso igual a todas as unidades:
<span class="math display">\[
(\hat{\mu}, \hat{\alpha}, \hat{\gamma}, \hat{\tau}^{DiD}) = \arg\min_{\mu, \alpha, \gamma, \tau}\ \sum_i \sum_t (y_{it} - \mu - \alpha_i - \gamma_t - D_{it}\tau)^2
\]</span></p>
<p>O <strong>SDiD</strong> combina ambos — efeitos fixos <em>e</em> pesos, tanto para unidades quanto para períodos:
<span class="math display">\[
(\hat{\mu}, \hat{\alpha}, \hat{\gamma}, \hat{\tau}^{SDiD}) = \arg\min_{\mu, \alpha, \gamma, \tau}\ \sum_i \sum_t (y_{it} - \mu - \alpha_i - \gamma_t - D_{it}\tau)^2 \hat{w}_i \hat{\lambda}_t
\]</span></p>
<p>Os pesos de unidade <span class="math inline">\(\hat{w}_i\)</span> balanceiam as tendências pré-tratamento: dão mais peso a unidades de controle cuja trajetória é similar à dos tratados. Os pesos temporais <span class="math inline">\(\hat{\lambda}_t\)</span> balanceiam os períodos: dão mais peso a períodos pré-tratamento cuja estrutura de cross-section é similar ao período pós. Em outras palavras, os pesos reponderam as observações de modo a reduzir o viés sob um modelo de fatores latentes, mesmo quando tendências paralelas globais não são válidas. Arkhangelsky et al. (2021) demonstram a consistência do SDiD sob um modelo de fatores quando as estimativas de pesos convergem adequadamente.</p>
<p><strong>O SDiD relaxa a suposição de tendências paralelas?</strong> A resposta exige uma distinção cuidadosa. O modelo que o SDiD <em>estima</em> é aditivo — <span class="math inline">\(\alpha_i + \gamma_t\)</span> — o mesmo do DiD. Nesse sentido, o SDiD não modela fatores interativos como o IFEct. Mas Arkhangelsky et al. (2021) demonstram que o SDiD é <strong>consistente sob um modelo de fatores latentes</strong> <span class="math inline">\(Y_{it}(0) = \alpha_i + \lambda&#39;_i f_t + \varepsilon_{it}\)</span> — um DGP em que tendências paralelas globais <em>não</em> valem. Como isso é possível?</p>
<p>A chave está nos pesos. Os pesos de unidade <span class="math inline">\(\hat{w}_i\)</span> são construídos para que a média ponderada dos controles tenha a <em>mesma tendência pré-tratamento</em> que os tratados. Os pesos temporais <span class="math inline">\(\hat{\lambda}_t\)</span> são construídos para que a média ponderada dos períodos pré-tratamento tenha a <em>mesma estrutura cross-section</em> que o período pós. Em conjunto, os pesos criam uma “vizinhança” local — um subconjunto reponderado de unidades e períodos — dentro da qual tendências paralelas valem aproximadamente, mesmo que não valham globalmente.</p>
<p><strong>Um exemplo concreto.</strong> Suponha três estados de controle: A (tendência crescente), B (tendência estável) e C (tendência decrescente). Se o estado tratado tem tendência estável no pré-tratamento, o DiD daria peso <span class="math inline">\(1/3\)</span> a cada controle e falharia (a média dos três não reproduz a tendência estável). O SDiD atribuiria peso alto a B (tendência similar) e pesos baixos a A e C — criando localmente uma comparação com tendências paralelas.</p>
<p><strong>Qual é o limite dessa tolerância?</strong> A consistência do SDiD sob o modelo de fatores depende de condições técnicas sobre a convergência dos pesos estimados (Arkhangelsky et al., 2021, Teorema 1). Na prática, isso requer que: (i) exista uma combinação convexa dos controles que reproduza a tendência dos tratados (ou seja, os tratados estejam no “envoltório convexo” dos controles em termos de cargas fatoriais <span class="math inline">\(\lambda_i\)</span>); e (ii) haja períodos pré-tratamento suficientes para estimar os pesos com precisão. Se a unidade tratada tem cargas fatoriais muito diferentes de <em>todos</em> os controles — por exemplo, se a Califórnia tem uma dinâmica única que nenhuma combinação de outros estados consegue reproduzir — os pesos não convergem e o SDiD não resolve o problema. Nesse cenário, seria necessário um estimador que modele os fatores diretamente, como o IFEct.</p>
<p>Em resumo: o SDiD não <em>modela</em> tendências não-paralelas (como o IFEct), mas <em>tolera</em> tendências não-paralelas via reponderação — desde que a heterogeneidade das tendências possa ser eliminada por uma recomposição convexa das unidades de controle. É mais robusto que o DiD, mas não tão flexível quanto o IFEct em cenários com estrutura fatorial complexa.</p>
<div id="implementação-no-r" class="section level3 hasAnchor" number="12.8.1">
<h3><span class="header-section-number">12.8.1</span> Implementação no R<a href="#implementa%C3%A7%C3%A3o-no-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Vamos aplicar DiD, SC e SDiD aos dados da Califórnia.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb139-1" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb139-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb139-2" tabindex="-1"></a></span>
<span id="cb139-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb139-3" tabindex="-1"></a>smoking_did <span class="ot">&lt;-</span> smoking <span class="sc">%&gt;%</span></span>
<span id="cb139-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb139-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">treatment =</span> <span class="fu">ifelse</span>(state <span class="sc">==</span> <span class="st">&quot;California&quot;</span> <span class="sc">&amp;</span> year <span class="sc">&gt;</span> <span class="dv">1988</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb139-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb139-5" tabindex="-1"></a>did <span class="ot">&lt;-</span> <span class="fu">feols</span>(cigsale <span class="sc">~</span> treatment <span class="sc">|</span> state <span class="sc">+</span> year, <span class="at">data =</span> smoking_did)</span>
<span id="cb139-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb139-6" tabindex="-1"></a></span>
<span id="cb139-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb139-7" tabindex="-1"></a><span class="fu">summary</span>(did)</span></code></pre></div>
<pre><code>## OLS estimation, Dep. Var.: cigsale
## Observations: 1,209
## Fixed-effects: state: 39,  year: 31
## Standard-errors: Clustered (state) 
##           Estimate Std. Error  t value           Pr(&gt;|t|)    
## treatment -27.3491    2.80238 -9.75925 0.0000000000066913 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## RMSE: 11.5     Adj. R2: 0.870229
##              Within R2: 0.032671</code></pre>
<p>O estimador de DiD assume tendências paralelas na média — suposição que pode não ser crível neste contexto, como mostra o event study:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-1" tabindex="-1"></a><span class="fu">library</span>(did2s)</span>
<span id="cb141-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-2" tabindex="-1"></a><span class="fu">library</span>(ggfixest)</span>
<span id="cb141-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-3" tabindex="-1"></a></span>
<span id="cb141-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-4" tabindex="-1"></a>df <span class="ot">&lt;-</span> smoking_did <span class="sc">%&gt;%</span></span>
<span id="cb141-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">event_time =</span> year <span class="sc">-</span> <span class="dv">1988</span>,</span>
<span id="cb141-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-6" tabindex="-1"></a>         <span class="at">id =</span> <span class="fu">as.integer</span>(<span class="fu">as.factor</span>(state))) <span class="sc">%&gt;%</span></span>
<span id="cb141-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-7" tabindex="-1"></a>  <span class="fu">group_by</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb141-8"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">g =</span> <span class="fu">ifelse</span>(state <span class="sc">==</span> <span class="st">&quot;California&quot;</span>, <span class="dv">1988</span>, <span class="dv">0</span>),</span>
<span id="cb141-9"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-9" tabindex="-1"></a>         <span class="at">cohort =</span> <span class="fu">ifelse</span>(state <span class="sc">==</span> <span class="st">&quot;California&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb141-10"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-10" tabindex="-1"></a>         <span class="at">g1 =</span> <span class="fu">ifelse</span>(state <span class="sc">==</span> <span class="st">&quot;California&quot;</span> <span class="sc">&amp;</span> year <span class="sc">&gt;=</span> <span class="dv">1980</span>, <span class="dv">1980</span>, <span class="dv">0</span>))</span>
<span id="cb141-11"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-11" tabindex="-1"></a></span>
<span id="cb141-12"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-12" tabindex="-1"></a>out_es <span class="ot">&lt;-</span> <span class="fu">event_study</span>(</span>
<span id="cb141-13"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-13" tabindex="-1"></a>  <span class="at">data =</span> df,</span>
<span id="cb141-14"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-14" tabindex="-1"></a>  <span class="at">idname =</span> <span class="st">&quot;id&quot;</span>,</span>
<span id="cb141-15"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-15" tabindex="-1"></a>  <span class="at">tname =</span> <span class="st">&quot;year&quot;</span>,</span>
<span id="cb141-16"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-16" tabindex="-1"></a>  <span class="at">gname =</span> <span class="st">&quot;g&quot;</span>,</span>
<span id="cb141-17"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-17" tabindex="-1"></a>  <span class="at">yname =</span> <span class="st">&quot;cigsale&quot;</span>,</span>
<span id="cb141-18"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-18" tabindex="-1"></a>  <span class="at">estimator =</span> <span class="st">&quot;all&quot;</span></span>
<span id="cb141-19"><a href="controle-sintético-e-estimação-contrafactual.html#cb141-19" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Error in create_Atheta_list_for_event_study(eventTime = eventTime, g_list = g_list,  : 
##   There are no comparison cohorts for the given eventTime</code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb143-1" tabindex="-1"></a><span class="fu">plot_event_study</span>(out_es)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:did1"></span>
<img src="bookdownproj_files/figure-html/did1-1.png" alt="Event study para o estimador de DiD aplicado ao exemplo da Califórnia." width="672" />
<p class="caption">
Figura 12.11: Event study para o estimador de DiD aplicado ao exemplo da Califórnia.
</p>
</div>
<p>Agora comparamos os três estimadores com o pacote <code>synthdid</code>:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-1" tabindex="-1"></a><span class="fu">library</span>(synthdid)</span>
<span id="cb144-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-2" tabindex="-1"></a></span>
<span id="cb144-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-3" tabindex="-1"></a>estimators <span class="ot">=</span> <span class="fu">list</span>(<span class="at">did=</span>did_estimate,</span>
<span id="cb144-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-4" tabindex="-1"></a>                  <span class="at">sc=</span>sc_estimate,</span>
<span id="cb144-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-5" tabindex="-1"></a>                  <span class="at">sdid=</span>synthdid_estimate)</span>
<span id="cb144-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-6" tabindex="-1"></a></span>
<span id="cb144-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-7" tabindex="-1"></a>df_sdid <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb144-8"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-8" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(state, year, cigsale, treatment) <span class="sc">%&gt;%</span></span>
<span id="cb144-9"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-9" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">treatment =</span> <span class="fu">as.integer</span>(treatment),</span>
<span id="cb144-10"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-10" tabindex="-1"></a>         <span class="at">year =</span> <span class="fu">as.integer</span>(year),</span>
<span id="cb144-11"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-11" tabindex="-1"></a>         <span class="at">state =</span> <span class="fu">as.factor</span>(state)) <span class="sc">%&gt;%</span></span>
<span id="cb144-12"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-12" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb144-13"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-13" tabindex="-1"></a></span>
<span id="cb144-14"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-14" tabindex="-1"></a>setup <span class="ot">&lt;-</span> <span class="fu">panel.matrices</span>(df_sdid)</span>
<span id="cb144-15"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-15" tabindex="-1"></a></span>
<span id="cb144-16"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-16" tabindex="-1"></a>estimates <span class="ot">&lt;-</span> <span class="fu">lapply</span>(estimators, <span class="cf">function</span>(estimator) { <span class="fu">estimator</span>(setup<span class="sc">$</span>Y,</span>
<span id="cb144-17"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-17" tabindex="-1"></a>                                                               setup<span class="sc">$</span>N0, setup<span class="sc">$</span>T0) } )</span>
<span id="cb144-18"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-18" tabindex="-1"></a></span>
<span id="cb144-19"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-19" tabindex="-1"></a>standard.errors <span class="ot">=</span> <span class="fu">mapply</span>(<span class="cf">function</span>(estimate, name) {</span>
<span id="cb144-20"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-20" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb144-21"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-21" tabindex="-1"></a>  <span class="cf">if</span>(name <span class="sc">==</span> <span class="st">&#39;mc&#39;</span>) { <span class="fu">mc_placebo_se</span>(setup<span class="sc">$</span>Y, setup<span class="sc">$</span>N0, setup<span class="sc">$</span>T0) }</span>
<span id="cb144-22"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-22" tabindex="-1"></a>  <span class="cf">else</span> {             <span class="fu">sqrt</span>(<span class="fu">vcov</span>(estimate, <span class="at">method=</span><span class="st">&#39;placebo&#39;</span>))     }</span>
<span id="cb144-23"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-23" tabindex="-1"></a>}, estimates, <span class="fu">names</span>(estimators))</span>
<span id="cb144-24"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-24" tabindex="-1"></a></span>
<span id="cb144-25"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-25" tabindex="-1"></a><span class="co"># Resultados</span></span>
<span id="cb144-26"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-26" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb144-27"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-27" tabindex="-1"></a>  <span class="at">Estimador =</span> <span class="fu">c</span>(<span class="st">&quot;DiD&quot;</span>, <span class="st">&quot;SC&quot;</span>, <span class="st">&quot;SDiD&quot;</span>),</span>
<span id="cb144-28"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-28" tabindex="-1"></a>  <span class="at">ATT =</span> <span class="fu">round</span>(<span class="fu">sapply</span>(estimates, <span class="cf">function</span>(x) x[<span class="dv">1</span>]), <span class="dv">2</span>),</span>
<span id="cb144-29"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-29" tabindex="-1"></a>  <span class="at">SE =</span> <span class="fu">round</span>(standard.errors, <span class="dv">2</span>)</span>
<span id="cb144-30"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-30" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb144-31"><a href="controle-sintético-e-estimação-contrafactual.html#cb144-31" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;Estimativas de ATT e erros-padrão para DiD, controle sintético e Synthetic DiD.&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:sdid">Tabela 12.5: </span>Estimativas de ATT e erros-padrão para DiD, controle sintético e Synthetic DiD.</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Estimador</th>
<th align="right">ATT</th>
<th align="right">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">did</td>
<td align="left">DiD</td>
<td align="right">-27.35</td>
<td align="right">17.74</td>
</tr>
<tr class="even">
<td align="left">sc</td>
<td align="left">SC</td>
<td align="right">-19.62</td>
<td align="right">9.92</td>
</tr>
<tr class="odd">
<td align="left">sdid</td>
<td align="left">SDiD</td>
<td align="right">-15.60</td>
<td align="right">8.37</td>
</tr>
</tbody>
</table>
<p>O gráfico a seguir compara visualmente as trajetórias estimadas:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb145-1" tabindex="-1"></a><span class="fu">synthdid_plot</span>(estimates[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="at">facet.vertical=</span><span class="cn">FALSE</span>,</span>
<span id="cb145-2"><a href="controle-sintético-e-estimação-contrafactual.html#cb145-2" tabindex="-1"></a>              <span class="at">control.name=</span><span class="st">&#39;control&#39;</span>, <span class="at">treated.name=</span><span class="st">&#39;california&#39;</span>,</span>
<span id="cb145-3"><a href="controle-sintético-e-estimação-contrafactual.html#cb145-3" tabindex="-1"></a>              <span class="at">lambda.comparable=</span><span class="cn">TRUE</span>, <span class="at">se.method =</span> <span class="st">&#39;none&#39;</span>,</span>
<span id="cb145-4"><a href="controle-sintético-e-estimação-contrafactual.html#cb145-4" tabindex="-1"></a>              <span class="at">trajectory.linetype =</span> <span class="dv">1</span>, <span class="at">line.width=</span>.<span class="dv">75</span>, <span class="at">effect.curvature=</span><span class="sc">-</span>.<span class="dv">4</span>,</span>
<span id="cb145-5"><a href="controle-sintético-e-estimação-contrafactual.html#cb145-5" tabindex="-1"></a>              <span class="at">trajectory.alpha=</span>.<span class="dv">7</span>, <span class="at">effect.alpha=</span>.<span class="dv">7</span>,</span>
<span id="cb145-6"><a href="controle-sintético-e-estimação-contrafactual.html#cb145-6" tabindex="-1"></a>              <span class="at">diagram.alpha=</span><span class="dv">1</span>, <span class="at">onset.alpha=</span>.<span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb145-7"><a href="controle-sintético-e-estimação-contrafactual.html#cb145-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="fu">c</span>(.<span class="dv">26</span>,.<span class="dv">07</span>), <span class="at">legend.direction=</span><span class="st">&#39;horizontal&#39;</span>,</span>
<span id="cb145-8"><a href="controle-sintético-e-estimação-contrafactual.html#cb145-8" tabindex="-1"></a>        <span class="at">legend.key=</span><span class="fu">element_blank</span>(), <span class="at">legend.background=</span><span class="fu">element_blank</span>(),</span>
<span id="cb145-9"><a href="controle-sintético-e-estimação-contrafactual.html#cb145-9" tabindex="-1"></a>        <span class="at">strip.background=</span><span class="fu">element_blank</span>(), <span class="at">strip.text.x =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:sdid1"></span>
<img src="bookdownproj_files/figure-html/sdid1-1.png" alt="Comparação visual das trajetórias estimadas por DiD, controle sintético e Synthetic DiD." width="672" />
<p class="caption">
Figura 12.12: Comparação visual das trajetórias estimadas por DiD, controle sintético e Synthetic DiD.
</p>
</div>
<p>E os pesos de unidade atribuídos por cada estimador:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="controle-sintético-e-estimação-contrafactual.html#cb146-1" tabindex="-1"></a><span class="fu">synthdid_units_plot</span>(<span class="fu">rev</span>(estimates[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]), <span class="at">se.method=</span><span class="st">&#39;none&#39;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:sdid2"></span>
<img src="bookdownproj_files/figure-html/sdid2-1.png" alt="Pesos de unidade atribuídos por DiD, controle sintético e Synthetic DiD." width="672" />
<p class="caption">
Figura 12.13: Pesos de unidade atribuídos por DiD, controle sintético e Synthetic DiD.
</p>
</div>
<p>Note que o DiD atribui peso igual a todos os estados de controle, o SC concentra peso em poucos estados similares à Califórnia, e o SDiD faz algo intermediário.</p>
</div>
</div>
<div id="trop-estimador-triplamente-robusto" class="section level2 hasAnchor" number="12.9">
<h2><span class="header-section-number">12.9</span> TROP: estimador triplamente robusto<a href="controle-sintético-e-estimação-contrafactual.html#trop-estimador-triplamente-robusto" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Athey, Imbens, Qu e Viviano (2025) propõem o <strong>TROP</strong> (<em>Triply Robust Panel Estimator</em>), que combina três componentes:</p>
<ol style="list-style-type: decimal">
<li>Um <strong>modelo de fatores</strong> (outcome model): <span class="math inline">\(Y_{it}(0) = \mu_i + \lambda&#39;_i f_t + \varepsilon_{it}\)</span></li>
<li><strong>Pesos de unidade</strong> <span class="math inline">\(w_i\)</span> (análogo ao SCM)</li>
<li><strong>Pesos temporais</strong> <span class="math inline">\(\omega_t\)</span> (análogo ao SDiD)</li>
</ol>
<p>A propriedade central do TROP é a <strong>tripla robustez</strong>. Para entender essa propriedade, considere que o viés do estimador tem uma estrutura <em>multiplicativa</em>: é proporcional ao produto de três termos de erro de especificação:
<span class="math display">\[
\text{viés} \propto e_{\text{modelo}} \times e_{\text{pesos de unidade}} \times e_{\text{pesos temporais}}
\]</span></p>
<p>onde <span class="math inline">\(e_{\text{modelo}}\)</span> é o erro do modelo de fatores, <span class="math inline">\(e_{\text{pesos de unidade}}\)</span> é o erro dos pesos de unidade, e <span class="math inline">\(e_{\text{pesos temporais}}\)</span> é o erro dos pesos temporais. Como o viés é um <em>produto</em> desses três termos, basta que <em>qualquer um</em> deles seja zero para que o viés total desapareça. Em outras palavras, o estimador é consistente se qualquer um dos três componentes estiver corretamente especificado — não é necessário que todos estejam corretos simultaneamente.</p>
<p>Isso contrasta com o SDiD, que usa efeitos fixos aditivos + pesos, enquanto o TROP usa um modelo de fatores + pesos. Contudo, é importante notar que quando <em>todos os três</em> componentes estão mal especificados, o viés pode ser arbitrário — a tripla robustez não protege contra falha simultânea de todos os componentes.</p>
<p>Em simulações, Athey et al. (2025) mostram que o TROP supera substancialmente o TWFE e compete com o SDiD e o MC em uma variedade de cenários. A recomendação dos autores é usar simulações calibradas aos dados para escolher entre estimadores — não há estimador que domine em todos os cenários.</p>
<p><strong>Nota</strong>: o artigo de Athey et al. (2025) é um <em>preprint</em> que ainda não passou por revisão por pares. Até 2026, não existe pacote R público para o TROP. A menção aqui é teórica e serve para situar o leitor na fronteira da literatura.</p>
</div>
<div id="quando-usar-cada-método-guia-prático" class="section level2 hasAnchor" number="12.10">
<h2><span class="header-section-number">12.10</span> Quando usar cada método: guia prático<a href="#quando-usar-cada-m%C3%A9todo-guia-pr%C3%A1tico" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A escolha entre os métodos depende do contexto empírico. Eis um guia baseado nas recomendações de Liu et al. (2024, p. 175):</p>
<p><strong>Árvore de decisão:</strong></p>
<ol style="list-style-type: decimal">
<li><strong>Uma única unidade tratada</strong> → SCM (seção 2) ou SCM aumentado (Ben-Michael et al., 2021)</li>
<li><strong>Múltiplas unidades, tendências paralelas plausíveis</strong> → DiD/FEct (capítulo 8 e seção 5.1)</li>
<li><strong>Múltiplas unidades, tendências paralelas duvidosas</strong> → IFEct ou MC (seção 5.2–5.3)</li>
<li><strong>Poucas unidades de controle</strong> → SDiD (seção 7) — os pesos ajudam a criar comparabilidade</li>
</ol>
<p><strong>Checklist prático</strong> (adaptado de Liu et al., 2024):</p>
<ol style="list-style-type: decimal">
<li>Visualize o <em>treatment status</em>: quando cada unidade entra no tratamento?</li>
<li>Visualize a variável resposta: há tendências não-paralelas visíveis?</li>
<li>Comece com FEct + diagnósticos (placebo test, equivalência)</li>
<li>Se os diagnósticos falharem → tente IFEct ou MC + diagnósticos</li>
<li>Se houver carryover → remova os períodos afetados e reestime</li>
<li>Compare as estimativas entre métodos: se concordarem, há robustez; se divergirem, investigue por quê</li>
</ol>
<p>A tabela abaixo resume as suposições e características de cada método:</p>
<table>
<caption><span id="tab:tabela-guia-metodos-scm">Tabela 12.6: </span>Resumo das suposições, pesos e pacotes dos principais estimadores contrafactuais discutidos no capítulo.</caption>
<colgroup>
<col width="6%" />
<col width="33%" />
<col width="20%" />
<col width="19%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Método</th>
<th align="left">Modelo para <span class="math inline">\(Y(0)\)</span></th>
<th align="left">Relaxa tendências paralelas?</th>
<th align="left">Pesos</th>
<th align="left">Pacote R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DiD/TWFE</td>
<td align="left"><span class="math inline">\(\alpha_i + \lambda_t\)</span></td>
<td align="left">Não</td>
<td align="left">Iguais</td>
<td align="left">fixest</td>
</tr>
<tr class="even">
<td align="left">FEct</td>
<td align="left"><span class="math inline">\(X&#39;\beta + \alpha_i + \xi_t\)</span></td>
<td align="left">Não (mesma suposição)</td>
<td align="left">Uniformes</td>
<td align="left">fect</td>
</tr>
<tr class="odd">
<td align="left">IFEct</td>
<td align="left"><span class="math inline">\(X&#39;\beta + \alpha_i + \xi_t + \lambda&#39;_i f_t\)</span></td>
<td align="left">Sim (fatores)</td>
<td align="left">Uniformes</td>
<td align="left">fect</td>
</tr>
<tr class="even">
<td align="left">MC</td>
<td align="left">Baixo posto (norma nuclear)</td>
<td align="left">Sim (baixo posto)</td>
<td align="left">Implícitos (norma nuclear)</td>
<td align="left">fect</td>
</tr>
<tr class="odd">
<td align="left">SCM</td>
<td align="left">Combinação convexa</td>
<td align="left">Indiretamente (via pesos)</td>
<td align="left">Convexos</td>
<td align="left">tidysynth</td>
</tr>
<tr class="even">
<td align="left">SDiD</td>
<td align="left"><span class="math inline">\(\alpha_i + \lambda_t\)</span> + pesos</td>
<td align="left">Indiretamente (via pesos)</td>
<td align="left">Unid. + tempo</td>
<td align="left">synthdid</td>
</tr>
<tr class="odd">
<td align="left">TROP</td>
<td align="left">Fatores + pesos</td>
<td align="left">Sim (tripla robustez)</td>
<td align="left">Unid. + tempo</td>
<td align="left">Sem pacote público até 2026</td>
</tr>
</tbody>
</table>
<p>A relação entre esses métodos envolve duas dimensões distintas. A primeira é a <strong>flexibilidade do modelo</strong>: DiD/FEct assumem efeitos aditivos, enquanto IFEct e MC permitem estrutura de fatores (baixo posto), relaxando tendências paralelas. A segunda é a <strong>robustez à má especificação</strong>: o SDiD usa o mesmo modelo aditivo do FEct, mas adiciona pesos de unidade e temporais que o tornam mais robusto quando tendências paralelas globais falham — é mais robusto, não necessariamente mais flexível. Da mesma forma, o TROP não relaxa suposições além do modelo de fatores; sua contribuição é a tripla robustez via estrutura multiplicativa do viés, que o protege contra erros em qualquer um dos três componentes. MC e IFEct operam sob suposições de baixo posto similares, mas diferem computacionalmente (<em>soft</em> vs. <em>hard impute</em>). Em todos os casos, métodos com menos suposições ou mais robustez tendem a pagar um custo em variância: a escolha envolve o trade-off viés-variância usual.</p>
</div>
<div id="resumo-2" class="section level2 hasAnchor" number="12.11">
<h2><span class="header-section-number">12.11</span> Resumo<a href="controle-sintético-e-estimação-contrafactual.html#resumo-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Neste capítulo, apresentamos uma família de métodos para estimação de efeitos causais em dados de painel, unificados pela ideia de <strong>imputação do contrafactual</strong> <span class="math inline">\(Y_{it}(0)\)</span>:</p>
<ul>
<li>O <strong>SCM</strong> constrói o contrafactual como combinação convexa de unidades não-tratadas — ideal para estudos de caso com uma unidade tratada.</li>
<li>O <strong>framework de estimação contrafactual</strong> (Liu et al., 2024) generaliza a imputação para três estimadores (FEct, IFEct, MC) com diagnósticos formais.</li>
<li>O <strong>SDiD</strong> combina pesos de unidade e temporais com efeitos fixos, criando tendências paralelas localmente.</li>
<li>O <strong>TROP</strong> (Athey et al., 2025) oferece tripla robustez combinando modelo de fatores com pesos de unidade e pesos temporais.</li>
</ul>
<p>A conexão com o capítulo 8 (DiD) é direta: o FEct é equivalente ao DiD por imputação de Borusyak et al. (2024), e o DiD tradicional é um caso especial do framework quando <span class="math inline">\(h(U_{it}) = \alpha_i + \xi_t\)</span>. A conexão com o capítulo 9 (TSCS) também é clara: o IFEct estende os modelos de fatores interativos de Xu (2017) e Gobillon e Magnac (2016) para o contexto de inferência causal.</p>
</div>
<div id="referências-3" class="section level2 hasAnchor" number="12.12">
<h2><span class="header-section-number">12.12</span> Referências<a href="#refer%C3%AAncias-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Abadie, A. (2021). Using synthetic controls: Feasibility, data requirements, and methodological aspects. <em>Journal of Economic Literature</em>, 59(2), 391–425.</p>
<p>Abadie, A., &amp; Gardeazabal, J. (2003). The economic costs of conflict: A case study of the Basque Country. <em>American Economic Review</em>, 93(1), 113–132.</p>
<p>Abadie, A., Diamond, A., &amp; Hainmueller, J. (2010). Synthetic control methods for comparative case studies: Estimating the effect of California’s tobacco control program. <em>Journal of the American Statistical Association</em>, 105(490), 493–505.</p>
<p>Abadie, A., Diamond, A., &amp; Hainmueller, J. (2015). Comparative politics and the synthetic control method. <em>American Journal of Political Science</em>, 59(2), 495–510.</p>
<p>Abadie, A., &amp; L’Hour, J. (2021). A penalized synthetic control estimator for disaggregated data. <em>Journal of the American Statistical Association</em>, 116(536), 1817–1834.</p>
<p>Arkhangelsky, D., Athey, S., Hirshberg, D. A., Imbens, G. W., &amp; Wager, S. (2021). Synthetic difference-in-differences. <em>American Economic Review</em>, 111(12), 4088–4118.</p>
<p>Arkhangelsky, D., &amp; Imbens, G. (2024). Causal models for longitudinal and panel data: A survey. <em>The Econometrics Journal</em>, 27(3), C1–C61.</p>
<p>Athey, S., Bayati, M., Doudchenko, N., Imbens, G., &amp; Khosravi, K. (2021). Matrix completion methods for causal panel data models. <em>Journal of the American Statistical Association</em>, 116(536), 1716–1730.</p>
<p>Athey, S., Imbens, G., Qu, Z., &amp; Viviano, D. (2025). Triply robust estimation of causal effects with missing data in panel studies. Preprint.</p>
<p>Ben-Michael, E., Feller, A., &amp; Rothstein, J. (2021). The augmented synthetic control method. <em>Journal of the American Statistical Association</em>, 116(536), 1789–1803.</p>
<p>Borusyak, K., Jaravel, X., &amp; Spiess, J. (2024). Revisiting event-study designs: Robust and efficient estimation. <em>Review of Economic Studies</em>, 91(6), 3253–3285.</p>
<p>Chernozhukov, V., Wüthrich, K., &amp; Zhu, Y. (2021). An exact and robust conformal inference method for counterfactual and synthetic controls. <em>Journal of the American Statistical Association</em>, 116(536), 1849–1864.</p>
<p>Doudchenko, N., &amp; Imbens, G. W. (2016). Balancing, regression, difference-in-differences and synthetic control methods: A synthesis. Working Paper 22791, National Bureau of Economic Research.</p>
<p>Gobillon, L., &amp; Magnac, T. (2016). Regional policy evaluation: Interactive fixed effects and synthetic controls. <em>Review of Economics and Statistics</em>, 98(3), 535–551.</p>
<p>Kaul, A., Klößner, S., Pfeifer, G., &amp; Schieler, M. (2022). Standard synthetic control methods: The case of using all preintervention outcomes together with covariates. <em>Journal of Business &amp; Economic Statistics</em>, 40(3), 1362–1376.</p>
<p>Liu, L., Wang, Y., &amp; Xu, Y. (2024). A practical guide to counterfactual estimators for causal inference with time-series cross-sectional data. <em>American Journal of Political Science</em>, 68(1), 160–176.</p>
<p>Robbins, M. W., Saunders, J., &amp; Kilmer, B. (2017). A framework for synthetic control methods with high-dimensional, micro-level data: Evaluating a neighborhood-specific crime intervention. <em>Journal of the American Statistical Association</em>, 112(517), 109–126.</p>
<p>Xu, Y. (2017). Generalized synthetic control method: Causal inference with interactive fixed effects models. <em>Political Analysis</em>, 25(1), 57–76.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="interferência-spillover-e-dinâmica.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="llms-e-outras.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/mgaldino/Causalidade/edit/main/11-Synth.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": "https://github.com/mgaldino/Causalidade/blob/main/11-Synth.Rmd",
    "text": null
  },
  "download": ["bookdownproj.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
